/////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////
//            Improved Smarter Twisted Rune Scripts
/////////////////////////////////////////////////////////////////////
// 				Version 1
// Layenne, 18th level Conjurer
// 
// Fixes: No bugfixes. 
//
// Important: Layenne will now actually use the Staff of the Magi!
// Basic strategy is taken from Sion in the Improved Guarded Compound:
// 
// Improvements: His spell picks are completely revamped. An 18th level
// Conjurer has 3 million XP, and in ToB would get to pick a Feat. We're
// being generous so we skip that (no Planetars). All of the weird
// contingencies and sequencers are replaced by a bunch of long-lived
// spells that are cast at warp speed as soon as you see him (stoneskin,
// etc). Just as the PCs tend to buff up with Strength and Chaotic Commands 
// before starting the day, Sion preps well. His basic combat strategy is
// to remove your buffs, cast malison, and then beat on you with Horrid
// Wiltin and Chaos until you submit. He won't go downstairs. He will
// rest and regain all of his spells if you leave him alone for an hour. 
//
// We completely ignore in-game memorization (hey, who doesn't?) and
// use global variables to keep track of spells. 
//
// Memorized Spells By Level: 6 6 7 6 6 7 6 6 6 
// Memorized Spells (number, name, spell level): 
//  6 magic missile (1)
//  6 total lvl 1 spells
//
//  2 melf acid (2)
//  2 Mirror Images (2)        
//  2 vocalize (2)
//  6 total lvl 2 spells
//
//  1 remove magic (3)
//  1 pro normal missiles
//  2 slow (3)
//  3 minute meteors (3)
//  7 total lvl 3 spells
//
//  1 greater malison (4)
//  3 stoneskin (4) 
//  1 Fireshield Blue (4)
//  1 Teleport Field (4)
//  6 total lvl 4 spells
//
//  2 spell immunity (5)
//  2 chaos (5)
//  1 Breach (5)
//  1 Shadow Door (5)
//  6 total lvl 5 spells
//
//  1 pro magic energy (6)
//  3 pro magic weapons (6)
//  1 improved haste (6)
//  1 Death Spell (6)
//  1 True Sight (6)
//  7 total lvl 6 spells
//
//  1 Spell Turning (7)
//  1 Summon Efreeti (7)
//  1 Summon Hakeashar (7)
//  2 Finger of Death (7)
//  1 Ruby Ray (7)
//  Cast Spell Sequencer (3x lvl 4 spells or lower)
//  6 total lvl 7 spells
//
//  3 wilting (8)
//  2 Maze (8)
//  1 Power Word, Blind (8)
//  Cast Spell Trigger (3x lvl 6 spells or lower)
//  6 total lvl 8 spells
//
//  2 Time Stop (9)
//  1 Summon Dark Planetar (9)
//  1 Spell Trap (9)
//  1 Improved Alacrity (9)
//  1 Spellstrike
//  6 total lvl 9 spells
/////////////////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////////////
// True Sight Stuff
/////////////////////////////////////////////////////////////////////
IF
  !GlobalTimerNotExpired("MO_EnemyTrueSightTimer","GLOBAL")
  Global("MO_EnemyTrueSight","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("MO_EnemyTrueSight","GLOBAL",0)
END

IF
  Global("MO_TrueSightActive","LOCALS",1)
  CheckStat(Myself,0,TRUE_SIGHT)
THEN
  RESPONSE #100
    SetGlobal("MO_TrueSightActive","LOCALS",0)
    SetGlobal("MO_EnemyTrueSight","GLOBAL",0)
END

/////////////////////////////////////////////////////////////////////
// Battle Prep
// 
// The TR crew knows you are invading, so they prepare by casting
// a few long-lived buffing spells right before you come in. 
/////////////////////////////////////////////////////////////////////
IF
  Allegiance(Myself,ENEMY)
  Global("Prep","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobalTimer("TimeStop","LOCALS",1)
    ReallyForceSpell(Myself,CLERIC_ZONE_OF_SWEET_AIR)
    ReallyForceSpell(Myself,WIZARD_STONE_SKIN)
    ReallyForceSpell(Myself,WIZARD_MIRROR_IMAGE)
    ReallyForceSpell(Myself,WIZARD_FIRE_SHIELD_BLUE)
    ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_MAGIC_ENERGY)
    ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
    ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_NORMAL_MISSILES)
    ReallyForceSpell(Myself,WIZARD_SPELL_IMMUNITY_DIVINATION)
    ReallyForceSpell(Myself,WIZARD_SPELL_IMMUNITY_ABJURATION)
    ReallyForceSpell(Myself,WIZARD_SPELL_TRAP)
    ReallyForceSpell("hlrevan",WIZARD_IMPROVED_HASTE)
    SetGlobal("Prep","LOCALS",1)
    EquipItem("staf11")
    GiveItemCreate("potn34",Myself,1,0,0)
    UseItem("potn34",Myself)
    // Lvl 9
    SetGlobal("Time","LOCALS",2)
    SetGlobal("ImprovedAlacrity","LOCALS",1)
    SetGlobal("DarkPlanetar","LOCALS",1)
    SetGlobal("Spellstrike","LOCALS",1)
    // Lvl 8
    SetGlobal("wilt","LOCALS",3)
    SetGlobal("Maze","LOCALS",2)
    SetGlobal("PWBlind","LOCALS",1)
    // Lvl 7
    SetGlobal("Turning","LOCALS",1)
    SetGlobal("Efreeti","LOCALS",1)
    SetGlobal("Hakeashar","LOCALS",1)
    SetGlobal("FingerDeath","LOCALS",2)
    SetGlobal("RubyRay","LOCALS",1)
    // Lvl 6
    SetGlobal("ProMagWeap","LOCALS",2)
    SetGlobal("DeathSpell","LOCALS",1)
    SetGlobal("TrueSight","LOCALS",1)
    // Lvl 5
    SetGlobal("Chaos","LOCALS",2)
    SetGlobal("Breach","LOCALS",1)
    SetGlobal("ShadowDoor","LOCALS",1)
    // Lvl 4
    SetGlobal("Stoneskin","LOCALS",2)
    SetGlobal("Malison","LOCALS",1)
    SetGlobal("Teleport","LOCALS",1)
    // Lvl 3
    SetGlobal("Thrust","LOCALS",1)
    SetGlobal("Slow","LOCALS",3)
    SetGlobal("Remove","LOCALS",1)
    // Lvl 2
    SetGlobal("Vocalize","LOCALS",2)
    SetGlobal("MelfAcid","LOCALS",2)
    SetGlobal("Mirror","LOCALS",1)
    // Lvl 1
    SetGlobal("Missile","LOCALS",6)
    Shout(100)	// wake everyone up!
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Locate the enemy. 
/////////////////////////////////////////////////////////////////////
IF
  !Detect([GOODCUTOFF])
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  !Detect(Player1)
  !Range(Player1,5)
THEN
  RESPONSE #100
    ForceSpell(Player1,WIZARD_DIMENSION_DOOR)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
END

// Going to exclude Sequencer and Trigger for now since already brutal. Can add later.

// Spell Trigger Options (3x level 6- spells)

// Spell Sequencer Options (3x level 4- spells)

/////////////////////////////////////////////////////////////////////
// Spell: Vocalize (if silenced)
/////////////////////////////////////////////////////////////////////
IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  See([GOODCUTOFF])
  GlobalGT("Vocalize","LOCALS",0)
  StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Vocalize","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(Myself,WIZARD_VOCALIZE)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Spell: Stoneskin (if out)
/////////////////////////////////////////////////////////////////////
IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  See(NearestEnemyOfType([GOODCUTOFF]))
  CheckStatLT(Myself,1,STONESKINS)
  GlobalGT("Stoneskin","LOCALS",0)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Stoneskin","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(Myself,WIZARD_STONE_SKIN)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Spell: Mirror Image
/////////////////////////////////////////////////////////////////////
IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  See(NearestEnemyOfType([GOODCUTOFF]))
  GlobalGT("Mirror","LOCALS",0)
  !StateCheck(Myself,STATE_MIRRORIMAGE)
  !CheckStatGT(NearestEnemyOf(Myself),0,TRUE_SIGHT)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,TRUE_SIGHT)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,TRUE_SIGHT)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,TRUE_SIGHT)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,TRUE_SIGHT)
  !CheckStatGT(SeventhNearestEnemyOf(Myself),0,TRUE_SIGHT)
  !CheckStatGT(EighthNearestEnemyOf(Myself),0,TRUE_SIGHT)
  !CheckStatGT(NinthNearestEnemyOf(Myself),0,TRUE_SIGHT)
  !CheckStatGT(TenthNearestEnemyOf(Myself),0,TRUE_SIGHT)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #50
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Mirror","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(Myself,WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
  RESPONSE #50
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Spell: Shadow door
/////////////////////////////////////////////////////////////////////
IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  See(NearestEnemyOfType([GOODCUTOFF]))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  GlobalGT("ShadowDoor","LOCALS",0)
  Range(LastSeenBy(Myself),5)
  !CheckStatGT(NearestEnemyOf(Myself),0,TRUE_SIGHT)
  !CheckStatGT(SecondNearestEnemyOf(Myself),0,TRUE_SIGHT)
  !CheckStatGT(ThirdNearestEnemyOf(Myself),0,TRUE_SIGHT)
  !CheckStatGT(FourthNearestEnemyOf(Myself),0,TRUE_SIGHT)
  !CheckStatGT(SixthNearestEnemyOf(Myself),0,TRUE_SIGHT)
  !CheckStatGT(SeventhNearestEnemyOf(Myself),0,TRUE_SIGHT)
  !CheckStatGT(EighthNearestEnemyOf(Myself),0,TRUE_SIGHT)
  !CheckStatGT(NinthNearestEnemyOf(Myself),0,TRUE_SIGHT)
  !CheckStatGT(TenthNearestEnemyOf(Myself),0,TRUE_SIGHT)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #50
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("ShadowDoor","LOCALS",-1)
    Spell(Myself,WIZARD_SHADOW_DOOR)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
  RESPONSE #50
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Spell: Spell Turning (if out)
/////////////////////////////////////////////////////////////////////
IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Allegiance(Myself,ENEMY)
  OR(6)
    See([GOODCUTOFF.0.0.MAGE_ALL])
    See([GOODCUTOFF.0.0.BARD_ALL])
    See([GOODCUTOFF.0.0.CLERIC_ALL])
    See([GOODCUTOFF.0.0.DRUID_ALL])
    See([GOODCUTOFF.0.0.SORCERER])
    See([GOODCUTOFF.0.0.CLERIC_MAGE])
  GlobalGT("Turning","LOCALS",0)
  CheckStatLT(Myself,1,WIZARD_SPELL_TURNING)
  !CheckStat(Myself,1,WIZARD_SPELL_TRAP)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Turning","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(Myself,WIZARD_SPELL_TURNING)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Spell: Pro Mag Weapon (if nearby enemy or attacked)
/////////////////////////////////////////////////////////////////////
IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  See(NearestEnemyOfType([GOODCUTOFF]))
  OR(2)
    See(LastAttackerOf(Myself))
    Range(LastSeenBy(Myself),4)
  GlobalGT("ProMagWeap","LOCALS",0)
  !CheckSpellState(Myself,PROTECTION_FROM_MAGICAL_WEAPONS)
  !CheckSpellState(Myself,ABSOLUTE_IMMUNITY)
  !CheckSpellState(Myself,MANTLE)
  !CheckSpellState(Myself,IMPROVED_MANTLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("ProMagWeap","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(Myself,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Spell: Time Stop
/////////////////////////////////////////////////////////////////////
IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  !GlobalTimerNotExpired("MO_TimeStopTimer","LOCALS")
  GlobalGT("Time","LOCALS",0)
  OR(2)
    See(NearestEnemyOfType([GOODCUTOFF]))
    ActuallyInCombat()
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_TimeStopTimer","LOCALS",18)
    IncrementGlobal("Time","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(Myself,WIZARD_TIME_STOP)  // SPWI909.SPL (Time Stop)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Spell: Improved Alacrity
/////////////////////////////////////////////////////////////////////
IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  See([GOODCUTOFF])
  Allegiance(Myself,ENEMY)
  GlobalGT("ImprovedAlacrity","LOCALS",0)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("ImprovedAlacrity","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(Myself,WIZARD_IMPROVED_ALACRITY)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Spell: Dark Planetar
/////////////////////////////////////////////////////////////////////
IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  See([GOODCUTOFF])
  Allegiance(Myself,ENEMY)
  GlobalGT("DarkPlanetar","LOCALS",0)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("DarkPlanetar","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(Myself,WIZARD_SUMMON_PLANATAR_EVIL)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// True Sight
/////////////////////////////////////////////////////////////////////
IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  GlobalGT("TrueSight","LOCALS",0)
  OR(6)
    SpellCast([GOODCUTOFF],WIZARD_PROJECT_IMAGE)  // SPWI703.SPL (Project Image)
    SpellCast([GOODCUTOFF],WIZARD_SIMULACRUM)  // SPWI804.SPL (Simulacrum)
    SpellCast([GOODCUTOFF],WIZARD_MISLEAD)  // SPWI607.SPL (Mislead)
    SpellCast([GOODCUTOFF],WIZARD_SHADOW_DOOR)  // SPWI505.SPL (Shadow Door)
    SpellCast([GOODCUTOFF],WIZARD_IMPROVED_INVISIBILITY)  // SPWI405.SPL (Improved Invisibility)
    SpellCast([GOODCUTOFF],WIZARD_INVISIBILITY)  // SPWI206.SPL (Invisibility)
  !CheckSpellState([GOODCUTOFF],SI_DIVINATION)
  Global("MO_EnemyTrueSight","GLOBAL",0)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
THEN
  RESPONSE #100
    SetGlobal("MO_TrueSightActive","LOCALS",1)
    SetGlobal("MO_EnemyTrueSight","GLOBAL",1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_EnemyTrueSightTimer","GLOBAL",60)
    IncrementGlobal("TrueSight","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  GlobalGT("TrueSight","LOCALS",0)
  Detect([GOODCUTOFF])
  OR(4)
    StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
    CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
    Gender(LastSeenBy(Myself),ILLUSIONARY)
  !CheckSpellState([GOODCUTOFF],SI_DIVINATION)
  Global("MO_EnemyTrueSight","GLOBAL",0)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
THEN
  RESPONSE #100
    SetGlobal("MO_TrueSightActive","LOCALS",1)
    SetGlobal("MO_EnemyTrueSight","GLOBAL",1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_EnemyTrueSightTimer","GLOBAL",60)
    IncrementGlobal("TrueSight","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  GlobalGT("TrueSight","LOCALS",0)
  See(NearestEnemyOfType([GOODCUTOFF]))
  OR(4)
    StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
    CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
    Gender(LastSeenBy(Myself),ILLUSIONARY)
  !CheckStat(LastSeenBy(Myself),3,WIZARD_SPELL_IMMUNITY)
  Global("MO_EnemyTrueSight","GLOBAL",0)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
THEN
  RESPONSE #100
    SetGlobal("MO_TrueSightActive","LOCALS",1)
    SetGlobal("MO_EnemyTrueSight","GLOBAL",1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_EnemyTrueSightTimer","GLOBAL",60)
    IncrementGlobal("TrueSight","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  GlobalGT("TrueSight","LOCALS",0)
  See(SecondNearestEnemyOfType([GOODCUTOFF]))
  OR(4)
    StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
    CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
    Gender(LastSeenBy(Myself),ILLUSIONARY)
  !CheckStat(LastSeenBy(Myself),3,WIZARD_SPELL_IMMUNITY)
  Global("MO_EnemyTrueSight","GLOBAL",0)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
THEN
  RESPONSE #100
    SetGlobal("MO_TrueSightActive","LOCALS",1)
    SetGlobal("MO_EnemyTrueSight","GLOBAL",1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_EnemyTrueSightTimer","GLOBAL",60)
    IncrementGlobal("TrueSight","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  GlobalGT("TrueSight","LOCALS",0)
  See(ThirdNearestEnemyOfType([GOODCUTOFF]))
  OR(4)
    StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
    CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
    Gender(LastSeenBy(Myself),ILLUSIONARY)
  !CheckStat(LastSeenBy(Myself),3,WIZARD_SPELL_IMMUNITY)
  Global("MO_EnemyTrueSight","GLOBAL",0)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
THEN
  RESPONSE #100
    SetGlobal("MO_TrueSightActive","LOCALS",1)
    SetGlobal("MO_EnemyTrueSight","GLOBAL",1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_EnemyTrueSightTimer","GLOBAL",60)
    IncrementGlobal("TrueSight","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  GlobalGT("TrueSight","LOCALS",0)
  See(FourthNearestEnemyOfType([GOODCUTOFF]))
  OR(4)
    StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
    CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
    Gender(LastSeenBy(Myself),ILLUSIONARY)
  !CheckStat(LastSeenBy(Myself),3,WIZARD_SPELL_IMMUNITY)
  Global("MO_EnemyTrueSight","GLOBAL",0)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
THEN
  RESPONSE #100
    SetGlobal("MO_TrueSightActive","LOCALS",1)
    SetGlobal("MO_EnemyTrueSight","GLOBAL",1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_EnemyTrueSightTimer","GLOBAL",60)
    IncrementGlobal("TrueSight","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  GlobalGT("TrueSight","LOCALS",0)
  See(FifthNearestEnemyOfType([GOODCUTOFF]))
  OR(4)
    StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
    CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
    Gender(LastSeenBy(Myself),ILLUSIONARY)
  !CheckStat(LastSeenBy(Myself),3,WIZARD_SPELL_IMMUNITY)
  Global("MO_EnemyTrueSight","GLOBAL",0)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
THEN
  RESPONSE #100
    SetGlobal("MO_TrueSightActive","LOCALS",1)
    SetGlobal("MO_EnemyTrueSight","GLOBAL",1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_EnemyTrueSightTimer","GLOBAL",60)
    IncrementGlobal("TrueSight","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  GlobalGT("TrueSight","LOCALS",0)
  See(SixthNearestEnemyOfType([GOODCUTOFF]))
  OR(4)
    StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
    CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
    Gender(LastSeenBy(Myself),ILLUSIONARY)
  !CheckStat(LastSeenBy(Myself),3,WIZARD_SPELL_IMMUNITY)
  Global("MO_EnemyTrueSight","GLOBAL",0)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
THEN
  RESPONSE #100
    SetGlobal("MO_TrueSightActive","LOCALS",1)
    SetGlobal("MO_EnemyTrueSight","GLOBAL",1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_EnemyTrueSightTimer","GLOBAL",60)
    IncrementGlobal("TrueSight","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Spell: Remove Magic
/////////////////////////////////////////////////////////////////////
IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  NumCreatureLT([GOODCUTOFF],4)
  See(NearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  GlobalGT("Remove","LOCALS",0)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  !CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Remove","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  NumCreatureLT([GOODCUTOFF],4)
  See(SecondNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  GlobalGT("Remove","LOCALS",0)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  !CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Remove","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  NumCreatureLT([GOODCUTOFF],4)
  See(ThirdNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  GlobalGT("Remove","LOCALS",0)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  !CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Remove","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  NumCreatureLT([GOODCUTOFF],4)
  See(FourthNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  GlobalGT("Remove","LOCALS",0)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  !CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Remove","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  NumCreatureLT([GOODCUTOFF],4)
  See(FifthNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  GlobalGT("Remove","LOCALS",0)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  !CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Remove","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  NumCreatureLT([GOODCUTOFF],4)
  See(SixthNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  GlobalGT("Remove","LOCALS",0)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  !CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Remove","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Spell: Breach
/////////////////////////////////////////////////////////////////////
IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  !GlobalTimerNotExpired("MO_TimeStopTimer","LOCALS")
  NumCreatureLT([GOODCUTOFF],4)
  See(NearestEnemyOfType([GOODCUTOFF]))
  GlobalGT("Breach","LOCALS",0)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Breach","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_BREACH)  // SPWI513.SPL (Breach)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  !GlobalTimerNotExpired("MO_TimeStopTimer","LOCALS")
  NumCreatureLT([GOODCUTOFF],4)
  See(SecondNearestEnemyOfType([GOODCUTOFF]))
  GlobalGT("Breach","LOCALS",0)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Breach","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_BREACH)  // SPWI513.SPL (Breach)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  !GlobalTimerNotExpired("MO_TimeStopTimer","LOCALS")
  NumCreatureLT([GOODCUTOFF],4)
  See(ThirdNearestEnemyOfType([GOODCUTOFF]))
  GlobalGT("Breach","LOCALS",0)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Breach","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_BREACH)  // SPWI513.SPL (Breach)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  !GlobalTimerNotExpired("MO_TimeStopTimer","LOCALS")
  NumCreatureLT([GOODCUTOFF],4)
  See(FourthNearestEnemyOfType([GOODCUTOFF]))
  GlobalGT("Breach","LOCALS",0)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Breach","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_BREACH)  // SPWI513.SPL (Breach)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  !GlobalTimerNotExpired("MO_TimeStopTimer","LOCALS")
  NumCreatureLT([GOODCUTOFF],4)
  See(FifthNearestEnemyOfType([GOODCUTOFF]))
  GlobalGT("Breach","LOCALS",0)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Breach","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_BREACH)  // SPWI513.SPL (Breach)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  !GlobalTimerNotExpired("MO_TimeStopTimer","LOCALS")
  NumCreatureLT([GOODCUTOFF],4)
  See(SixthNearestEnemyOfType([GOODCUTOFF]))
  GlobalGT("Breach","LOCALS",0)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Breach","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_BREACH)  // SPWI513.SPL (Breach)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Spell: Spell Thrust
/////////////////////////////////////////////////////////////////////
IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  !GlobalTimerNotExpired("MO_TimeStopTimer","LOCALS")
  NumCreatureLT([GOODCUTOFF],4)
  See(NearestEnemyOfType([GOODCUTOFF]))
  GlobalGT("Thrust","LOCALS",0)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(3)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
    CheckSpellState(LastSeenBy(Myself),SI_DIVINATION)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Thrust","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_SPELL_THRUST)  // SPWI321.SPL (Spell Thrust)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  !GlobalTimerNotExpired("MO_TimeStopTimer","LOCALS")
  NumCreatureLT([GOODCUTOFF],4)
  See(SecondNearestEnemyOfType([GOODCUTOFF]))
  GlobalGT("Thrust","LOCALS",0)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(3)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
    CheckSpellState(LastSeenBy(Myself),SI_DIVINATION)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Thrust","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_SPELL_THRUST)  // SPWI321.SPL (Spell Thrust)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  !GlobalTimerNotExpired("MO_TimeStopTimer","LOCALS")
  NumCreatureLT([GOODCUTOFF],4)
  See(ThirdNearestEnemyOfType([GOODCUTOFF]))
  GlobalGT("Thrust","LOCALS",0)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(3)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
    CheckSpellState(LastSeenBy(Myself),SI_DIVINATION)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Thrust","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_SPELL_THRUST)  // SPWI321.SPL (Spell Thrust)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  !GlobalTimerNotExpired("MO_TimeStopTimer","LOCALS")
  NumCreatureLT([GOODCUTOFF],4)
  See(FourthNearestEnemyOfType([GOODCUTOFF]))
  GlobalGT("Thrust","LOCALS",0)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(3)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
    CheckSpellState(LastSeenBy(Myself),SI_DIVINATION)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Thrust","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_SPELL_THRUST)  // SPWI321.SPL (Spell Thrust)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  !GlobalTimerNotExpired("MO_TimeStopTimer","LOCALS")
  NumCreatureLT([GOODCUTOFF],4)
  See(FifthNearestEnemyOfType([GOODCUTOFF]))
  GlobalGT("Thrust","LOCALS",0)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(3)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
    CheckSpellState(LastSeenBy(Myself),SI_DIVINATION)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Thrust","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_SPELL_THRUST)  // SPWI321.SPL (Spell Thrust)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  !GlobalTimerNotExpired("MO_TimeStopTimer","LOCALS")
  NumCreatureLT([GOODCUTOFF],4)
  See(SixthNearestEnemyOfType([GOODCUTOFF]))
  GlobalGT("Thrust","LOCALS",0)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(3)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
    CheckSpellState(LastSeenBy(Myself),SI_DIVINATION)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Thrust","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_SPELL_THRUST)  // SPWI321.SPL (Spell Thrust)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Spell: Ruby Ray
/////////////////////////////////////////////////////////////////////
IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  !GlobalTimerNotExpired("MO_TimeStopTimer","LOCALS")
  NumCreatureLT([GOODCUTOFF],4)
  See(NearestEnemyOfType([GOODCUTOFF]))
  GlobalGT("RubyRay","LOCALS",0)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(7)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
    CheckSpellState(LastSeenBy(Myself),SI_DIVINATION)
    CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("RubyRay","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  !GlobalTimerNotExpired("MO_TimeStopTimer","LOCALS")
  NumCreatureLT([GOODCUTOFF],4)
  See(SecondNearestEnemyOfType([GOODCUTOFF]))
  GlobalGT("RubyRay","LOCALS",0)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(7)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
    CheckSpellState(LastSeenBy(Myself),SI_DIVINATION)
    CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("RubyRay","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  !GlobalTimerNotExpired("MO_TimeStopTimer","LOCALS")
  NumCreatureLT([GOODCUTOFF],4)
  See(ThirdNearestEnemyOfType([GOODCUTOFF]))
  GlobalGT("RubyRay","LOCALS",0)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(7)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
    CheckSpellState(LastSeenBy(Myself),SI_DIVINATION)
    CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("RubyRay","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  !GlobalTimerNotExpired("MO_TimeStopTimer","LOCALS")
  NumCreatureLT([GOODCUTOFF],4)
  See(FourthNearestEnemyOfType([GOODCUTOFF]))
  GlobalGT("RubyRay","LOCALS",0)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(7)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
    CheckSpellState(LastSeenBy(Myself),SI_DIVINATION)
    CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("RubyRay","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  !GlobalTimerNotExpired("MO_TimeStopTimer","LOCALS")
  NumCreatureLT([GOODCUTOFF],4)
  See(FifthNearestEnemyOfType([GOODCUTOFF]))
  GlobalGT("RubyRay","LOCALS",0)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(7)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
    CheckSpellState(LastSeenBy(Myself),SI_DIVINATION)
    CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("RubyRay","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  !GlobalTimerNotExpired("MO_TimeStopTimer","LOCALS")
  NumCreatureLT([GOODCUTOFF],4)
  See(SixthNearestEnemyOfType([GOODCUTOFF]))
  GlobalGT("RubyRay","LOCALS",0)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(7)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
    CheckSpellState(LastSeenBy(Myself),SI_DIVINATION)
    CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("RubyRay","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Spell: Spellstrike
/////////////////////////////////////////////////////////////////////
IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  !GlobalTimerNotExpired("MO_TimeStopTimer","LOCALS")
  NumCreatureLT([GOODCUTOFF],4)
  See(NearestEnemyOfType([GOODCUTOFF]))
  GlobalGT("Spellstrike","LOCALS",0)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Spellstrike","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_SPELL_STRIKE)  // SPWI903.SPL (Spellstrike)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  !GlobalTimerNotExpired("MO_TimeStopTimer","LOCALS")
  NumCreatureLT([GOODCUTOFF],4)
  See(SecondNearestEnemyOfType([GOODCUTOFF]))
  GlobalGT("Spellstrike","LOCALS",0)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Spellstrike","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_SPELL_STRIKE)  // SPWI903.SPL (Spellstrike)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  !GlobalTimerNotExpired("MO_TimeStopTimer","LOCALS")
  NumCreatureLT([GOODCUTOFF],4)
  See(ThirdNearestEnemyOfType([GOODCUTOFF]))
  GlobalGT("Spellstrike","LOCALS",0)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Spellstrike","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_SPELL_STRIKE)  // SPWI903.SPL (Spellstrike)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  !GlobalTimerNotExpired("MO_TimeStopTimer","LOCALS")
  NumCreatureLT([GOODCUTOFF],4)
  See(FourthNearestEnemyOfType([GOODCUTOFF]))
  GlobalGT("Spellstrike","LOCALS",0)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Spellstrike","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_SPELL_STRIKE)  // SPWI903.SPL (Spellstrike)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  !GlobalTimerNotExpired("MO_TimeStopTimer","LOCALS")
  NumCreatureLT([GOODCUTOFF],4)
  See(FifthNearestEnemyOfType([GOODCUTOFF]))
  GlobalGT("Spellstrike","LOCALS",0)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Spellstrike","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_SPELL_STRIKE)  // SPWI903.SPL (Spellstrike)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  !GlobalTimerNotExpired("MO_TimeStopTimer","LOCALS")
  NumCreatureLT([GOODCUTOFF],4)
  See(SixthNearestEnemyOfType([GOODCUTOFF]))
  GlobalGT("Spellstrike","LOCALS",0)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Spellstrike","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_SPELL_STRIKE)  // SPWI903.SPL (Spellstrike)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Spell Type Determination
/////////////////////////////////////////////////////////////////////
IF
  RandomNum(2,1)
THEN
  RESPONSE #100
    SetGlobal("MO_Offensive","LOCALS",1)
    Continue()
END

IF
  RandomNum(2,2)
THEN
  RESPONSE #100
    SetGlobal("MO_Offensive","LOCALS",0)
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Offensive Spells
/////////////////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////////////
// Spell: Death Spell
/////////////////////////////////////////////////////////////////////
IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  See([GOODCUTOFF.0.0.0.0.SUMMONED])
  GlobalGT("DeathSpell","LOCALS",0)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #80
    SetGlobal("MO_CastDeathSpell","LOCALS",1)
    Continue()
  RESPONSE #20
    SetGlobal("MO_CastDeathSpell","LOCALS",0)
    Continue()
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastDeathSpell","LOCALS",1)
  See(Nearest([GOODCUTOFF.0.0.0.0.SUMMONED]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  GlobalGT("DeathSpell","LOCALS",0)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("DeathSpell","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DEATH_SPELL)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastDeathSpell","LOCALS",1)
  See(SecondNearest([GOODCUTOFF.0.0.0.0.SUMMONED]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  GlobalGT("DeathSpell","LOCALS",0)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("DeathSpell","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DEATH_SPELL)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastDeathSpell","LOCALS",1)
  See(ThirdNearest([GOODCUTOFF.0.0.0.0.SUMMONED]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  GlobalGT("DeathSpell","LOCALS",0)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("DeathSpell","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DEATH_SPELL)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastDeathSpell","LOCALS",1)
  See(FourthNearest([GOODCUTOFF.0.0.0.0.SUMMONED]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  GlobalGT("DeathSpell","LOCALS",0)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("DeathSpell","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DEATH_SPELL)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastDeathSpell","LOCALS",1)
  See(FifthNearest([GOODCUTOFF.0.0.0.0.SUMMONED]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  GlobalGT("DeathSpell","LOCALS",0)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("DeathSpell","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DEATH_SPELL)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastDeathSpell","LOCALS",1)
  See(SixthNearest([GOODCUTOFF.0.0.0.0.SUMMONED]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  GlobalGT("DeathSpell","LOCALS",0)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("DeathSpell","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DEATH_SPELL)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Spell: Wilting
/////////////////////////////////////////////////////////////////////
IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  See([GOODCUTOFF])
  GlobalGT("Wilt","LOCALS",0)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #60
    SetGlobal("MO_CastAbiDalzim","LOCALS",1)
    Continue()
  RESPONSE #40
    SetGlobal("MO_CastAbiDalzim","LOCALS",0)
    Continue()
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastAbiDalzim","LOCALS",1)
  See(NearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  GlobalGT("Wilt","LOCALS",0)
  !CheckSpellState(LastSeenBy(Myself),SI_NECROMANCY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),80,RESISTMAGIC)
  CheckStatLT(LastSeenBy(Myself),80,MAGICDAMAGERESISTANCE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Wilt","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastAbiDalzim","LOCALS",1)
  See(SecondNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  GlobalGT("Wilt","LOCALS",0)
  !CheckSpellState(LastSeenBy(Myself),SI_NECROMANCY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),80,RESISTMAGIC)
  CheckStatLT(LastSeenBy(Myself),80,MAGICDAMAGERESISTANCE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Wilt","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastAbiDalzim","LOCALS",1)
  See(ThirdNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  GlobalGT("Wilt","LOCALS",0)
  !CheckSpellState(LastSeenBy(Myself),SI_NECROMANCY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),80,RESISTMAGIC)
  CheckStatLT(LastSeenBy(Myself),80,MAGICDAMAGERESISTANCE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Wilt","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastAbiDalzim","LOCALS",1)
  See(FourthNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  GlobalGT("Wilt","LOCALS",0)
  !CheckSpellState(LastSeenBy(Myself),SI_NECROMANCY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),80,RESISTMAGIC)
  CheckStatLT(LastSeenBy(Myself),80,MAGICDAMAGERESISTANCE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Wilt","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastAbiDalzim","LOCALS",1)
  See(FifthNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  GlobalGT("Wilt","LOCALS",0)
  !CheckSpellState(LastSeenBy(Myself),SI_NECROMANCY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),80,RESISTMAGIC)
  CheckStatLT(LastSeenBy(Myself),80,MAGICDAMAGERESISTANCE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Wilt","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastAbiDalzim","LOCALS",1)
  See(SixthNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  GlobalGT("Wilt","LOCALS",0)
  !CheckSpellState(LastSeenBy(Myself),SI_NECROMANCY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),80,RESISTMAGIC)
  CheckStatLT(LastSeenBy(Myself),80,MAGICDAMAGERESISTANCE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Wilt","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Spell: Finger of Death
/////////////////////////////////////////////////////////////////////
IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  See([GOODCUTOFF])
  GlobalGT("FingerDeath","LOCALS",0)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #50
    SetGlobal("MO_CastFingerDeath","LOCALS",1)
    Continue()
  RESPONSE #50
    SetGlobal("MO_CastFingerDeath","LOCALS",0)
    Continue()
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastFingerDeath","LOCALS",1)
  See(NearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  GlobalGT("FingerDeath","LOCALS",0)
  !HasItemEquiped("clck26",LastSeenBy(Myself))  // Cloak of Mirroring
  !CheckStat(LastSeenBy(Myself),1,DEATH_WARD)
  !CheckSpellState(LastSeenBy(Myself),SI_NECROMANCY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),40,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("FingerDeath","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastFingerDeath","LOCALS",1)
  See(SecondNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  GlobalGT("FingerDeath","LOCALS",0)
  !HasItemEquiped("clck26",LastSeenBy(Myself))  // Cloak of Mirroring
  !CheckStat(LastSeenBy(Myself),1,DEATH_WARD)
  !CheckSpellState(LastSeenBy(Myself),SI_NECROMANCY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),40,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("FingerDeath","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastFingerDeath","LOCALS",1)
  See(ThirdNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  GlobalGT("FingerDeath","LOCALS",0)
  !HasItemEquiped("clck26",LastSeenBy(Myself))  // Cloak of Mirroring
  !CheckStat(LastSeenBy(Myself),1,DEATH_WARD)
  !CheckSpellState(LastSeenBy(Myself),SI_NECROMANCY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),40,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("FingerDeath","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastFingerDeath","LOCALS",1)
  See(FourthNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  GlobalGT("FingerDeath","LOCALS",0)
  !HasItemEquiped("clck26",LastSeenBy(Myself))  // Cloak of Mirroring
  !CheckStat(LastSeenBy(Myself),1,DEATH_WARD)
  !CheckSpellState(LastSeenBy(Myself),SI_NECROMANCY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),40,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("FingerDeath","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastFingerDeath","LOCALS",1)
  See(FifthNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  GlobalGT("FingerDeath","LOCALS",0)
  !HasItemEquiped("clck26",LastSeenBy(Myself))  // Cloak of Mirroring
  !CheckStat(LastSeenBy(Myself),1,DEATH_WARD)
  !CheckSpellState(LastSeenBy(Myself),SI_NECROMANCY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),40,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("FingerDeath","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastFingerDeath","LOCALS",1)
  See(SixthNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  GlobalGT("FingerDeath","LOCALS",0)
  !HasItemEquiped("clck26",LastSeenBy(Myself))  // Cloak of Mirroring
  !CheckStat(LastSeenBy(Myself),1,DEATH_WARD)
  !CheckSpellState(LastSeenBy(Myself),SI_NECROMANCY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),40,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("FingerDeath","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Spell: Summon Hakeashar
/////////////////////////////////////////////////////////////////////
IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  See([GOODCUTOFF])
  GlobalGT("Hakeashar","LOCALS",0)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #50
    SetGlobal("MO_CastHakeashar","LOCALS",1)
    Continue()
  RESPONSE #50
    SetGlobal("MO_CastHakeashar","LOCALS",0)
    Continue()
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastHakeashar","LOCALS",1)
  See(NearestEnemyOfType([GOODCUTOFF]))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  GlobalGT("Hakeashar","LOCALS",0)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  OR(5)
    Class(LastSeenBy(Myself),MAGE_ALL)
    Class(LastSeenBy(Myself),BARD_ALL)
    Class(LastSeenBy(Myself),CLERIC_ALL)
    Class(LastSeenBy(Myself),DRUID_ALL)
    Class(LastSeenBy(Myself),SORCERER)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Hakeashar","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_SUMMON_HAKEASHAR)  // SPWI719.SPL (Summon Hakeashar)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastHakeashar","LOCALS",1)
  See(SecondNearestEnemyOfType([GOODCUTOFF]))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  GlobalGT("Hakeashar","LOCALS",0)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  OR(5)
    Class(LastSeenBy(Myself),MAGE_ALL)
    Class(LastSeenBy(Myself),BARD_ALL)
    Class(LastSeenBy(Myself),CLERIC_ALL)
    Class(LastSeenBy(Myself),DRUID_ALL)
    Class(LastSeenBy(Myself),SORCERER)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Hakeashar","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_SUMMON_HAKEASHAR)  // SPWI719.SPL (Summon Hakeashar)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastHakeashar","LOCALS",1)
  See(ThirdNearestEnemyOfType([GOODCUTOFF]))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  GlobalGT("Hakeashar","LOCALS",0)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  OR(5)
    Class(LastSeenBy(Myself),MAGE_ALL)
    Class(LastSeenBy(Myself),BARD_ALL)
    Class(LastSeenBy(Myself),CLERIC_ALL)
    Class(LastSeenBy(Myself),DRUID_ALL)
    Class(LastSeenBy(Myself),SORCERER)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Hakeashar","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_SUMMON_HAKEASHAR)  // SPWI719.SPL (Summon Hakeashar)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastHakeashar","LOCALS",1)
  See(FourthNearestEnemyOfType([GOODCUTOFF]))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  GlobalGT("Hakeashar","LOCALS",0)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  OR(5)
    Class(LastSeenBy(Myself),MAGE_ALL)
    Class(LastSeenBy(Myself),BARD_ALL)
    Class(LastSeenBy(Myself),CLERIC_ALL)
    Class(LastSeenBy(Myself),DRUID_ALL)
    Class(LastSeenBy(Myself),SORCERER)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Hakeashar","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_SUMMON_HAKEASHAR)  // SPWI719.SPL (Summon Hakeashar)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastHakeashar","LOCALS",1)
  See(FifthNearestEnemyOfType([GOODCUTOFF]))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  GlobalGT("Hakeashar","LOCALS",0)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  OR(5)
    Class(LastSeenBy(Myself),MAGE_ALL)
    Class(LastSeenBy(Myself),BARD_ALL)
    Class(LastSeenBy(Myself),CLERIC_ALL)
    Class(LastSeenBy(Myself),DRUID_ALL)
    Class(LastSeenBy(Myself),SORCERER)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Hakeashar","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_SUMMON_HAKEASHAR)  // SPWI719.SPL (Summon Hakeashar)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastHakeashar","LOCALS",1)
  See(SixthNearestEnemyOfType([GOODCUTOFF]))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  GlobalGT("Hakeashar","LOCALS",0)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  OR(5)
    Class(LastSeenBy(Myself),MAGE_ALL)
    Class(LastSeenBy(Myself),BARD_ALL)
    Class(LastSeenBy(Myself),CLERIC_ALL)
    Class(LastSeenBy(Myself),DRUID_ALL)
    Class(LastSeenBy(Myself),SORCERER)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Hakeashar","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_SUMMON_HAKEASHAR)  // SPWI719.SPL (Summon Hakeashar)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Spell: Summon Efreeti
/////////////////////////////////////////////////////////////////////
IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  See([GOODCUTOFF])
  Allegiance(Myself,ENEMY)
  GlobalGT("Efreeti","LOCALS",0)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #50
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Efreeti","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(Myself,WIZARD_SUMMON_EFREET)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
  RESPONSE #50
  	Continue()
END

/////////////////////////////////////////////////////////////////////
// Spell: Melf Acid
/////////////////////////////////////////////////////////////////////
IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  See([GOODCUTOFF])
  GlobalGT("MelfAcid","LOCALS",0)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #50
    SetGlobal("MO_CastAcidArrow","LOCALS",1)
    Continue()
  RESPONSE #50
    SetGlobal("MO_CastAcidArrow","LOCALS",0)
    Continue()
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastAcidArrow","LOCALS",1)
  GlobalGT("MelfAcid","LOCALS",0)
  See(NearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  !HasItem("clck26",LastSeenBy(Myself))
  !HasItemEquiped("shld24",LastSeenBy(Myself))
  !Gender(LastSeenBy(Myself),SUMMONED)
  CheckStatLT(LastSeenBy(Myself),90,RESISTACID)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("MelfAcid","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastAcidArrow","LOCALS",1)
  GlobalGT("MelfAcid","LOCALS",0)
  See(SecondNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  !HasItem("clck26",LastSeenBy(Myself))
  !HasItemEquiped("shld24",LastSeenBy(Myself))
  !Gender(LastSeenBy(Myself),SUMMONED)
  CheckStatLT(LastSeenBy(Myself),90,RESISTACID)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("MelfAcid","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastAcidArrow","LOCALS",1)
  GlobalGT("MelfAcid","LOCALS",0)
  See(ThirdNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  !HasItem("clck26",LastSeenBy(Myself))
  !HasItemEquiped("shld24",LastSeenBy(Myself))
  !Gender(LastSeenBy(Myself),SUMMONED)
  CheckStatLT(LastSeenBy(Myself),90,RESISTACID)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("MelfAcid","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastAcidArrow","LOCALS",1)
  GlobalGT("MelfAcid","LOCALS",0)
  See(FourthNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  !HasItem("clck26",LastSeenBy(Myself))
  !HasItemEquiped("shld24",LastSeenBy(Myself))
  !Gender(LastSeenBy(Myself),SUMMONED)
  CheckStatLT(LastSeenBy(Myself),90,RESISTACID)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("MelfAcid","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastAcidArrow","LOCALS",1)
  GlobalGT("MelfAcid","LOCALS",0)
  See(FifthNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  !HasItem("clck26",LastSeenBy(Myself))
  !HasItemEquiped("shld24",LastSeenBy(Myself))
  !Gender(LastSeenBy(Myself),SUMMONED)
  CheckStatLT(LastSeenBy(Myself),90,RESISTACID)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("MelfAcid","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastAcidArrow","LOCALS",1)
  GlobalGT("MelfAcid","LOCALS",0)
  See(SixthNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  !HasItem("clck26",LastSeenBy(Myself))
  !HasItemEquiped("shld24",LastSeenBy(Myself))
  !Gender(LastSeenBy(Myself),SUMMONED)
  CheckStatLT(LastSeenBy(Myself),90,RESISTACID)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("MelfAcid","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Spell: Magic Missile
/////////////////////////////////////////////////////////////////////
IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  See([GOODCUTOFF])
  GlobalGT("Missile","LOCALS",0)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #50
    SetGlobal("MO_CastMagicMissile","LOCALS",1)
    Continue()
  RESPONSE #50
    SetGlobal("MO_CastMagicMissile","LOCALS",0)
    Continue()
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastMagicMissile","LOCALS",1)
  GlobalGT("Missile","LOCALS",0)
  See(NearestEnemyOfType([GOODCUTOFF]))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  !HasItemEquiped("clck26",LastSeenBy(Myself))
  !HasItemEquiped("shld24",LastSeenBy(Myself))
  !Gender(LastSeenBy(Myself),SUMMONED)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(LastSeenBy(Myself),SI_EVOCATION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100    
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Missile","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastMagicMissile","LOCALS",1)
  GlobalGT("Missile","LOCALS",0)
  See(SecondNearestEnemyOfType([GOODCUTOFF]))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  !HasItemEquiped("clck26",LastSeenBy(Myself))
  !HasItemEquiped("shld24",LastSeenBy(Myself))
  !Gender(LastSeenBy(Myself),SUMMONED)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(LastSeenBy(Myself),SI_EVOCATION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100    
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Missile","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastMagicMissile","LOCALS",1)
  GlobalGT("Missile","LOCALS",0)
  See(ThirdNearestEnemyOfType([GOODCUTOFF]))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  !HasItemEquiped("clck26",LastSeenBy(Myself))
  !HasItemEquiped("shld24",LastSeenBy(Myself))
  !Gender(LastSeenBy(Myself),SUMMONED)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(LastSeenBy(Myself),SI_EVOCATION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100    
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Missile","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastMagicMissile","LOCALS",1)
  GlobalGT("Missile","LOCALS",0)
  See(FourthNearestEnemyOfType([GOODCUTOFF]))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  !HasItemEquiped("clck26",LastSeenBy(Myself))
  !HasItemEquiped("shld24",LastSeenBy(Myself))
  !Gender(LastSeenBy(Myself),SUMMONED)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(LastSeenBy(Myself),SI_EVOCATION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100    
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Missile","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastMagicMissile","LOCALS",1)
  GlobalGT("Missile","LOCALS",0)
  See(FifthNearestEnemyOfType([GOODCUTOFF]))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  !HasItemEquiped("clck26",LastSeenBy(Myself))
  !HasItemEquiped("shld24",LastSeenBy(Myself))
  !Gender(LastSeenBy(Myself),SUMMONED)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(LastSeenBy(Myself),SI_EVOCATION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100    
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Missile","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastMagicMissile","LOCALS",1)
  GlobalGT("Missile","LOCALS",0)
  See(SixthNearestEnemyOfType([GOODCUTOFF]))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  !HasItemEquiped("clck26",LastSeenBy(Myself))
  !HasItemEquiped("shld24",LastSeenBy(Myself))
  !Gender(LastSeenBy(Myself),SUMMONED)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(LastSeenBy(Myself),SI_EVOCATION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100    
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Missile","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Disabling Spells
/////////////////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////////////
// Spell: Teleport Field
/////////////////////////////////////////////////////////////////////
IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  See(NearestEnemyOfType([GOODCUTOFF]))
  GlobalGT("Teleport","LOCALS",0)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #50
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Teleport","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(Myself,WIZARD_TELEPORT_FIELD)  // SPWI421.SPL (Teleport Field)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
  RESPONSE #50
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Spell: Maze
/////////////////////////////////////////////////////////////////////
IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  See([GOODCUTOFF])
  GlobalGT("Maze","LOCALS",0)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #50
    SetGlobal("MO_CastMaze","LOCALS",1)
    Continue()
  RESPONSE #50
    SetGlobal("MO_CastMaze","LOCALS",0)
    Continue()
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  !GlobalTimerNotExpired("MO_MazeTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  Global("MO_CastMaze","LOCALS",1)
  See(NearestEnemyOfType([GOODCUTOFF]))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  Range(LastSeenBy(Myself),4)
  GlobalGT("Maze","LOCALS",0)
  !Gender(LastSeenBy(Myself),SUMMONED)
  CheckStatLT(LastSeenBy(Myself),18,INT)
  !CheckSpellState(LastSeenBy(Myself),CHAOTIC_COMMANDS)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !Kit(LastSeenBy(Myself),BERSERKER)
  !Kit(LastSeenBy(Myself),BARBARIAN)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_MazeTimer","LOCALS",18)
    IncrementGlobal("Maze","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MAZE)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  !GlobalTimerNotExpired("MO_MazeTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  Global("MO_CastMaze","LOCALS",1)
  See(SecondNearestEnemyOfType([GOODCUTOFF]))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  Range(LastSeenBy(Myself),4)
  GlobalGT("Maze","LOCALS",0)
  !Gender(LastSeenBy(Myself),SUMMONED)
  CheckStatLT(LastSeenBy(Myself),18,INT)
  !CheckSpellState(LastSeenBy(Myself),CHAOTIC_COMMANDS)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !Kit(LastSeenBy(Myself),BERSERKER)
  !Kit(LastSeenBy(Myself),BARBARIAN)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_MazeTimer","LOCALS",18)
    IncrementGlobal("Maze","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MAZE)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  !GlobalTimerNotExpired("MO_MazeTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  Global("MO_CastMaze","LOCALS",1)
  See(ThirdNearestEnemyOfType([GOODCUTOFF]))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  Range(LastSeenBy(Myself),4)
  GlobalGT("Maze","LOCALS",0)
  !Gender(LastSeenBy(Myself),SUMMONED)
  CheckStatLT(LastSeenBy(Myself),18,INT)
  !CheckSpellState(LastSeenBy(Myself),CHAOTIC_COMMANDS)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !Kit(LastSeenBy(Myself),BERSERKER)
  !Kit(LastSeenBy(Myself),BARBARIAN)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_MazeTimer","LOCALS",18)
    IncrementGlobal("Maze","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MAZE)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  !GlobalTimerNotExpired("MO_MazeTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  Global("MO_CastMaze","LOCALS",1)
  See(FourthNearestEnemyOfType([GOODCUTOFF]))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  Range(LastSeenBy(Myself),4)
  GlobalGT("Maze","LOCALS",0)
  !Gender(LastSeenBy(Myself),SUMMONED)
  CheckStatLT(LastSeenBy(Myself),18,INT)
  !CheckSpellState(LastSeenBy(Myself),CHAOTIC_COMMANDS)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !Kit(LastSeenBy(Myself),BERSERKER)
  !Kit(LastSeenBy(Myself),BARBARIAN)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_MazeTimer","LOCALS",18)
    IncrementGlobal("Maze","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MAZE)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  !GlobalTimerNotExpired("MO_MazeTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  Global("MO_CastMaze","LOCALS",1)
  See(FifthNearestEnemyOfType([GOODCUTOFF]))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  Range(LastSeenBy(Myself),4)
  GlobalGT("Maze","LOCALS",0)
  !Gender(LastSeenBy(Myself),SUMMONED)
  CheckStatLT(LastSeenBy(Myself),18,INT)
  !CheckSpellState(LastSeenBy(Myself),CHAOTIC_COMMANDS)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !Kit(LastSeenBy(Myself),BERSERKER)
  !Kit(LastSeenBy(Myself),BARBARIAN)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_MazeTimer","LOCALS",18)
    IncrementGlobal("Maze","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MAZE)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  !GlobalTimerNotExpired("MO_MazeTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  Global("MO_CastMaze","LOCALS",1)
  See(SixthNearestEnemyOfType([GOODCUTOFF]))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  Range(LastSeenBy(Myself),4)
  GlobalGT("Maze","LOCALS",0)
  !Gender(LastSeenBy(Myself),SUMMONED)
  CheckStatLT(LastSeenBy(Myself),18,INT)
  !CheckSpellState(LastSeenBy(Myself),CHAOTIC_COMMANDS)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !Kit(LastSeenBy(Myself),BERSERKER)
  !Kit(LastSeenBy(Myself),BARBARIAN)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_MazeTimer","LOCALS",18)
    IncrementGlobal("Maze","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MAZE)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Spell: Greater Malison
/////////////////////////////////////////////////////////////////////
IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  See([GOODCUTOFF])
  GlobalGT("Malison","LOCALS",0)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #80
    SetGlobal("MO_CastMalison","LOCALS",1)
    Continue()
  RESPONSE #20
    SetGlobal("MO_CastMalison","LOCALS",0)
    Continue()
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  GlobalGT("Malison","LOCALS",0)
  Global("MO_CastMalison","LOCALS",1)
  See(NearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  !CheckSpellState(LastSeenBy(Myself),MALISON)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !CheckSpellState(LastSeenBy(Myself),SI_ENCHANTMENT)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Malison","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  GlobalGT("Malison","LOCALS",0)
  Global("MO_CastMalison","LOCALS",1)
  See(SecondNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  !CheckSpellState(LastSeenBy(Myself),MALISON)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !CheckSpellState(LastSeenBy(Myself),SI_ENCHANTMENT)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Malison","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  GlobalGT("Malison","LOCALS",0)
  Global("MO_CastMalison","LOCALS",1)
  See(ThirdNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  !CheckSpellState(LastSeenBy(Myself),MALISON)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !CheckSpellState(LastSeenBy(Myself),SI_ENCHANTMENT)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Malison","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  GlobalGT("Malison","LOCALS",0)
  Global("MO_CastMalison","LOCALS",1)
  See(FourthNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  !CheckSpellState(LastSeenBy(Myself),MALISON)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !CheckSpellState(LastSeenBy(Myself),SI_ENCHANTMENT)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Malison","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  GlobalGT("Malison","LOCALS",0)
  Global("MO_CastMalison","LOCALS",1)
  See(FifthNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  !CheckSpellState(LastSeenBy(Myself),MALISON)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !CheckSpellState(LastSeenBy(Myself),SI_ENCHANTMENT)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Malison","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  GlobalGT("Malison","LOCALS",0)
  Global("MO_CastMalison","LOCALS",1)
  See(SixthNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  !CheckSpellState(LastSeenBy(Myself),MALISON)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !CheckSpellState(LastSeenBy(Myself),SI_ENCHANTMENT)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Malison","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Spell: Slow
/////////////////////////////////////////////////////////////////////
IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  See([GOODCUTOFF])
  GlobalGT("Slow","LOCALS",0)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #50
    SetGlobal("MO_CastSlow","LOCALS",1)
    Continue()
  RESPONSE #50
    SetGlobal("MO_CastSlow","LOCALS",0)
    Continue()
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  Global("MO_CastSlow","LOCALS",1)
  See(NearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  GlobalGT("Slow","LOCALS",0)
  !Class(LastSeenBy(Myself),MONK)
  !HasItemEquiped("ring09",LastSeenBy(Myself))
  !CheckSpellState(LastSeenBy(Myself),SI_TRANSMUTATION)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !StateCheck(LastSeenBy(Myself),STATE_SLOWED)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Slow","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_SLOW)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  Global("MO_CastSlow","LOCALS",1)
  See(SecondNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  GlobalGT("Slow","LOCALS",0)
  !Class(LastSeenBy(Myself),MONK)
  !HasItemEquiped("ring09",LastSeenBy(Myself))
  !CheckSpellState(LastSeenBy(Myself),SI_TRANSMUTATION)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !StateCheck(LastSeenBy(Myself),STATE_SLOWED)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Slow","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_SLOW)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  Global("MO_CastSlow","LOCALS",1)
  See(ThirdNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  GlobalGT("Slow","LOCALS",0)
  !Class(LastSeenBy(Myself),MONK)
  !HasItemEquiped("ring09",LastSeenBy(Myself))
  !CheckSpellState(LastSeenBy(Myself),SI_TRANSMUTATION)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !StateCheck(LastSeenBy(Myself),STATE_SLOWED)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Slow","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_SLOW)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  Global("MO_CastSlow","LOCALS",1)
  See(FourthNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  GlobalGT("Slow","LOCALS",0)
  !Class(LastSeenBy(Myself),MONK)
  !HasItemEquiped("ring09",LastSeenBy(Myself))
  !CheckSpellState(LastSeenBy(Myself),SI_TRANSMUTATION)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !StateCheck(LastSeenBy(Myself),STATE_SLOWED)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Slow","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_SLOW)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  Global("MO_CastSlow","LOCALS",1)
  See(FifthNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  GlobalGT("Slow","LOCALS",0)
  !Class(LastSeenBy(Myself),MONK)
  !HasItemEquiped("ring09",LastSeenBy(Myself))
  !CheckSpellState(LastSeenBy(Myself),SI_TRANSMUTATION)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !StateCheck(LastSeenBy(Myself),STATE_SLOWED)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Slow","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_SLOW)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  Global("MO_CastSlow","LOCALS",1)
  See(SixthNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  GlobalGT("Slow","LOCALS",0)
  !Class(LastSeenBy(Myself),MONK)
  !HasItemEquiped("ring09",LastSeenBy(Myself))
  !CheckSpellState(LastSeenBy(Myself),SI_TRANSMUTATION)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !StateCheck(LastSeenBy(Myself),STATE_SLOWED)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Slow","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_SLOW)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Spell: Power Word, Blind
/////////////////////////////////////////////////////////////////////
IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  See([GOODCUTOFF])
  GlobalGT("PWBlind","LOCALS",0)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  Global("MO_WildMagicArea","LOCALS",0)
THEN
  RESPONSE #50
    SetGlobal("MO_CastPowerWordBlind","LOCALS",1)
    Continue()
  RESPONSE #50
    SetGlobal("MO_CastPowerWordBlind","LOCALS",0)
    Continue()
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  Global("MO_CastPowerWordBlind","LOCALS",1)
  See(NearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  GlobalGT("PWBlind","LOCALS",0)
  !HasItemEquiped("NPMISC1",LastSeenBy(Myself))
  !Gender(LastSeenBy(Myself),SUMMONED)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  !StateCheck(LastSeenBy(Myself),STATE_BLIND)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("PWBlind","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_POWER_WORD_BLIND)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  Global("MO_CastPowerWordBlind","LOCALS",1)
  See(SecondNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  GlobalGT("PWBlind","LOCALS",0)
  !HasItemEquiped("NPMISC1",LastSeenBy(Myself))
  !Gender(LastSeenBy(Myself),SUMMONED)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  !StateCheck(LastSeenBy(Myself),STATE_BLIND)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("PWBlind","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_POWER_WORD_BLIND)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  Global("MO_CastPowerWordBlind","LOCALS",1)
  See(ThirdNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  GlobalGT("PWBlind","LOCALS",0)
  !HasItemEquiped("NPMISC1",LastSeenBy(Myself))
  !Gender(LastSeenBy(Myself),SUMMONED)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  !StateCheck(LastSeenBy(Myself),STATE_BLIND)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("PWBlind","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_POWER_WORD_BLIND)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  Global("MO_CastPowerWordBlind","LOCALS",1)
  See(FourthNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  GlobalGT("PWBlind","LOCALS",0)
  !HasItemEquiped("NPMISC1",LastSeenBy(Myself))
  !Gender(LastSeenBy(Myself),SUMMONED)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  !StateCheck(LastSeenBy(Myself),STATE_BLIND)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("PWBlind","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_POWER_WORD_BLIND)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  Global("MO_CastPowerWordBlind","LOCALS",1)
  See(FifthNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  GlobalGT("PWBlind","LOCALS",0)
  !HasItemEquiped("NPMISC1",LastSeenBy(Myself))
  !Gender(LastSeenBy(Myself),SUMMONED)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  !StateCheck(LastSeenBy(Myself),STATE_BLIND)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("PWBlind","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_POWER_WORD_BLIND)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  Global("MO_CastPowerWordBlind","LOCALS",1)
  See(SixthNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  GlobalGT("PWBlind","LOCALS",0)
  !HasItemEquiped("NPMISC1",LastSeenBy(Myself))
  !Gender(LastSeenBy(Myself),SUMMONED)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  !StateCheck(LastSeenBy(Myself),STATE_BLIND)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("PWBlind","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_POWER_WORD_BLIND)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Spell: Chaos
/////////////////////////////////////////////////////////////////////
IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  See([GOODCUTOFF])
  GlobalGT("Chaos","LOCALS",0)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #50
    SetGlobal("MO_CastChaos","LOCALS",1)
    Continue()
  RESPONSE #50
    SetGlobal("MO_CastChaos","LOCALS",0)
    Continue()
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  Global("MO_CastChaos","LOCALS",1)
  See(NearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  GlobalGT("Chaos","LOCALS",0)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_DISABLED)
  CheckStatLT(LastSeenBy(Myself),20,RESISTMAGIC)
  CheckStatGT(LastSeenBy(Myself),-2,SAVEVSSPELL)
  !CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
  !CheckSpellState(LastSeenBy(Myself),SI_ENCHANTMENT)
  !CheckSpellState(LastSeenBy(Myself),BARBARIAN_RAGE)
  !CheckSpellState(LastSeenBy(Myself),BERSERKER_RAGE)
  !CheckSpellState(LastSeenBy(Myself),POTION_OF_CLARITY)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !HasItemEquiped("AMUL17",LastSeenBy(Myself)) // Greenstone Amulet
  !HasItemEquiped("LEAT20",LastSeenBy(Myself)) // Aeger's Hide +3
  !HasItemEquiped("SHLD25",LastSeenBy(Myself)) // Shield of Harmony +2
  !HasItemEquipedReal("SW1H54",LastSeenBy(Myself)) // The Equalizer
  !HasItemEquipedReal("SW2H14",LastSeenBy(Myself)) // Lilarcor
  !HasItemEquipedReal("SW2H21",LastSeenBy(Myself)) // Psion's Blade +5
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Chaos","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_CHAOS)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  Global("MO_CastChaos","LOCALS",1)
  See(SecondNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  GlobalGT("Chaos","LOCALS",0)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_DISABLED)
  CheckStatLT(LastSeenBy(Myself),20,RESISTMAGIC)
  CheckStatGT(LastSeenBy(Myself),-2,SAVEVSSPELL)
  !CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
  !CheckSpellState(LastSeenBy(Myself),SI_ENCHANTMENT)
  !CheckSpellState(LastSeenBy(Myself),BARBARIAN_RAGE)
  !CheckSpellState(LastSeenBy(Myself),BERSERKER_RAGE)
  !CheckSpellState(LastSeenBy(Myself),POTION_OF_CLARITY)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !HasItemEquiped("AMUL17",LastSeenBy(Myself)) // Greenstone Amulet
  !HasItemEquiped("LEAT20",LastSeenBy(Myself)) // Aeger's Hide +3
  !HasItemEquiped("SHLD25",LastSeenBy(Myself)) // Shield of Harmony +2
  !HasItemEquipedReal("SW1H54",LastSeenBy(Myself)) // The Equalizer
  !HasItemEquipedReal("SW2H14",LastSeenBy(Myself)) // Lilarcor
  !HasItemEquipedReal("SW2H21",LastSeenBy(Myself)) // Psion's Blade +5
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Chaos","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_CHAOS)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  Global("MO_CastChaos","LOCALS",1)
  See(ThirdNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  GlobalGT("Chaos","LOCALS",0)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_DISABLED)
  CheckStatLT(LastSeenBy(Myself),20,RESISTMAGIC)
  CheckStatGT(LastSeenBy(Myself),-2,SAVEVSSPELL)
  !CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
  !CheckSpellState(LastSeenBy(Myself),SI_ENCHANTMENT)
  !CheckSpellState(LastSeenBy(Myself),BARBARIAN_RAGE)
  !CheckSpellState(LastSeenBy(Myself),BERSERKER_RAGE)
  !CheckSpellState(LastSeenBy(Myself),POTION_OF_CLARITY)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !HasItemEquiped("AMUL17",LastSeenBy(Myself)) // Greenstone Amulet
  !HasItemEquiped("LEAT20",LastSeenBy(Myself)) // Aeger's Hide +3
  !HasItemEquiped("SHLD25",LastSeenBy(Myself)) // Shield of Harmony +2
  !HasItemEquipedReal("SW1H54",LastSeenBy(Myself)) // The Equalizer
  !HasItemEquipedReal("SW2H14",LastSeenBy(Myself)) // Lilarcor
  !HasItemEquipedReal("SW2H21",LastSeenBy(Myself)) // Psion's Blade +5
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Chaos","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_CHAOS)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  Global("MO_CastChaos","LOCALS",1)
  See(FourthNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  GlobalGT("Chaos","LOCALS",0)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_DISABLED)
  CheckStatLT(LastSeenBy(Myself),20,RESISTMAGIC)
  CheckStatGT(LastSeenBy(Myself),-2,SAVEVSSPELL)
  !CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
  !CheckSpellState(LastSeenBy(Myself),SI_ENCHANTMENT)
  !CheckSpellState(LastSeenBy(Myself),BARBARIAN_RAGE)
  !CheckSpellState(LastSeenBy(Myself),BERSERKER_RAGE)
  !CheckSpellState(LastSeenBy(Myself),POTION_OF_CLARITY)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !HasItemEquiped("AMUL17",LastSeenBy(Myself)) // Greenstone Amulet
  !HasItemEquiped("LEAT20",LastSeenBy(Myself)) // Aeger's Hide +3
  !HasItemEquiped("SHLD25",LastSeenBy(Myself)) // Shield of Harmony +2
  !HasItemEquipedReal("SW1H54",LastSeenBy(Myself)) // The Equalizer
  !HasItemEquipedReal("SW2H14",LastSeenBy(Myself)) // Lilarcor
  !HasItemEquipedReal("SW2H21",LastSeenBy(Myself)) // Psion's Blade +5
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Chaos","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_CHAOS)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  Global("MO_CastChaos","LOCALS",1)
  See(FifthNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  GlobalGT("Chaos","LOCALS",0)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_DISABLED)
  CheckStatLT(LastSeenBy(Myself),20,RESISTMAGIC)
  CheckStatGT(LastSeenBy(Myself),-2,SAVEVSSPELL)
  !CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
  !CheckSpellState(LastSeenBy(Myself),SI_ENCHANTMENT)
  !CheckSpellState(LastSeenBy(Myself),BARBARIAN_RAGE)
  !CheckSpellState(LastSeenBy(Myself),BERSERKER_RAGE)
  !CheckSpellState(LastSeenBy(Myself),POTION_OF_CLARITY)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !HasItemEquiped("AMUL17",LastSeenBy(Myself)) // Greenstone Amulet
  !HasItemEquiped("LEAT20",LastSeenBy(Myself)) // Aeger's Hide +3
  !HasItemEquiped("SHLD25",LastSeenBy(Myself)) // Shield of Harmony +2
  !HasItemEquipedReal("SW1H54",LastSeenBy(Myself)) // The Equalizer
  !HasItemEquipedReal("SW2H14",LastSeenBy(Myself)) // Lilarcor
  !HasItemEquipedReal("SW2H21",LastSeenBy(Myself)) // Psion's Blade +5
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Chaos","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_CHAOS)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  Global("MO_CastChaos","LOCALS",1)
  See(SixthNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  GlobalGT("Chaos","LOCALS",0)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_DISABLED)
  CheckStatLT(LastSeenBy(Myself),20,RESISTMAGIC)
  CheckStatGT(LastSeenBy(Myself),-2,SAVEVSSPELL)
  !CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
  !CheckSpellState(LastSeenBy(Myself),SI_ENCHANTMENT)
  !CheckSpellState(LastSeenBy(Myself),BARBARIAN_RAGE)
  !CheckSpellState(LastSeenBy(Myself),BERSERKER_RAGE)
  !CheckSpellState(LastSeenBy(Myself),POTION_OF_CLARITY)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !HasItemEquiped("AMUL17",LastSeenBy(Myself)) // Greenstone Amulet
  !HasItemEquiped("LEAT20",LastSeenBy(Myself)) // Aeger's Hide +3
  !HasItemEquiped("SHLD25",LastSeenBy(Myself)) // Shield of Harmony +2
  !HasItemEquipedReal("SW1H54",LastSeenBy(Myself)) // The Equalizer
  !HasItemEquipedReal("SW2H14",LastSeenBy(Myself)) // Lilarcor
  !HasItemEquipedReal("SW2H21",LastSeenBy(Myself)) // Psion's Blade +5
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("Chaos","LOCALS",-1)
    SetInterrupt(FALSE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_CHAOS)
    ApplySpell(Myself,WIZARD_INVISIBILITY)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Better part of valor 
/////////////////////////////////////////////////////////////////////
IF
  Global("ShangalarMove","AR1008",2)
  Allegiance(Myself,ENEMY)
  !GlobalTimerExpired("Cast","LOCALS")
  Range(NearestEnemyOf(Myself),4)
THEN
  RESPONSE #100
    RunAwayFrom(NearestEnemyOf(Myself),3)
END

/////////////////////////////////////////////////////////////////////
// Wait for death. :-) Don't let some other BG script take over. 
/////////////////////////////////////////////////////////////////////
IF
  True()
THEN
  RESPONSE #100
    NoAction()
END