// Selfish Joneleth - Round 1

IF
  !GlobalTimerNotExpired("MO_EnemyTrueSightTimer","GLOBAL")
  Global("MO_EnemyTrueSight","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("MO_EnemyTrueSight","GLOBAL",0)
END

IF
  Global("MO_TrueSightActive","LOCALS",1)
  CheckStat(Myself,0,TRUE_SIGHT)
THEN
  RESPONSE #100
    SetGlobal("MO_TrueSightActive","LOCALS",0)
    SetGlobal("MO_EnemyTrueSight","GLOBAL",0)
END

/////////////////////////////////////////////////////////////////////
// Prep
/////////////////////////////////////////////////////////////////////
IF
  See(NearestEnemyOf(Myself))
  Global("Prep","LOCALS",0)
THEN
  RESPONSE #100
    ApplySpell(Myself,WIZARD_STONE_SKIN)  // SPWI408.SPL (Stoneskin)
    ApplySpell(Myself,WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
    ApplySpell(Myself,WIZARD_SPELL_SHIELD)  // SPWI519.SPL (Spell Shield)
    ApplySpell(Myself,WIZARD_SPELL_TURNING)  // SPWI701.SPL (Spell Turning)
    ApplySpell(Myself,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)  // SPWI611.SPL (Protection From Magical Weapons)
    ApplySpell(Myself,WIZARD_SPELL_IMMUNITY_ABJURATION)  // SPWI590.SPL (Immunity: Abjuration)
    ApplySpell(Myself,WIZARD_SPELL_TRAP)  // SPWI902.SPL (Spell Trap)
    SetGlobal("Prep","LOCALS",1)
END

IF
  See(NearestEnemyOf(Myself))
  CheckStatLT(Myself,1,STONESKINS)
  TookDamage()
  Global("Prep2","LOCALS",0)
THEN
  RESPONSE #100
    DisplayString(Myself,3302)  // Chain Contingency—Spell Turning
    ApplySpell(Myself,WIZARD_SPELL_TURNING)  // SPWI701.SPL (Spell Turning)
    DisplayString(Myself,40240)  // Chain Contingency—Mislead
    ApplySpell(Myself,WIZARD_MISLEAD)  // SPWI607.SPL (Mislead)
    SetGlobal("Prep2","LOCALS",1)
END

IF
  See(NearestEnemyOf(Myself))
  CheckStatLT(Myself,1,STONESKINS)
  TookDamage()
  Global("Prep2","LOCALS",1)
THEN
  RESPONSE #100
    DisplayString(Myself,40252)  // Contingency—Protection From Magical Weapons
    ApplySpell(Myself,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)  // SPWI611.SPL (Protection From Magical Weapons)
    SetGlobal("Prep2","LOCALS",2)
END

/////////////////////////////////////////////////////////////////////
// Improved Alactrity - Used ONLY after Time Stop
/////////////////////////////////////////////////////////////////////
IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  GlobalTimerNotExpired("MO_TimeStopTimer","LOCALS")
  HaveSpell(WIZARD_IMPROVED_ALUCRITY)  // SPWI921.SPL (Improved Alacrity)
  OR(2)
    See(NearestEnemyOfType([GOODCUTOFF]))
    ActuallyInCombat()
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_IMPROVED_ALUCRITY)  // SPWI921.SPL (Improved Alacrity)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// TACTICS Shenanigans
/////////////////////////////////////////////////////////////////////
IF
  !GlobalTimerNotExpired("Spawn","LOCALS")
  !InMyArea("lich01")
  Difficulty(HARDEST)
THEN
  RESPONSE #100
    SetGlobalTimer("Spawn","LOCALS",30)
    CreateCreatureObjectOffScreen("lich01",Myself,0,0,0)
    Continue()
END

IF
  OR(7)
    See(Player1)
    See(Player2)
    See(Player3)
    See(Player4)
    See(Player5)
    See(Player6)
    See(NearestEnemyOf(Myself))
  False()
THEN
  RESPONSE #100
END

IF
  !GlobalTimerNotExpired("MySpell","LOCALS")
  !Allegiance(LastSeenBy(Myself),ENEMY)
THEN
  RESPONSE #100
    SetGlobalTimer("MySpell","LOCALS",18)
    ReallyForceSpellRES("ii0",LastSeenBy(Myself))
    Wait(2)
END

/////////////////////////////////////////////////////////////////////
// Defensive
/////////////////////////////////////////////////////////////////////
IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  See(NearestEnemyOfType([GOODCUTOFF]))
  HaveSpell(WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
  !CheckSpellState(Myself,PROTECTION_FROM_MAGICAL_WEAPONS)
  !CheckSpellState(Myself,ABSOLUTE_IMMUNITY)
  !CheckSpellState(Myself,MANTLE)
  !CheckSpellState(Myself,IMPROVED_MANTLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  See([GOODCUTOFF])
  HaveSpell(WIZARD_VOCALIZE)  // SPWI219.SPL (Vocalize)
  StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_VOCALIZE)  // SPWI219.SPL (Vocalize)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  See(NearestEnemyOfType([GOODCUTOFF]))
  CheckStatLT(Myself,1,STONESKINS)
  HaveSpell(WIZARD_STONE_SKIN)  // SPWI408.SPL (Stoneskin)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_STONE_SKIN)  // SPWI408.SPL (Stoneskin)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")  
  See(NearestEnemyOfType([GOODCUTOFF]))
  CheckStatLT(Myself,2,STONESKINS)
  HaveSpell(WIZARD_IMPROVED_INVISIBILITY)
  !CheckSpellState(Myself,CANNOT_TURN_INVISIBLE)
  !StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_IMPROVED_INVISIBILITY)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Time Stop
/////////////////////////////////////////////////////////////////////
IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  !GlobalTimerNotExpired("MO_TimeStopTimer","LOCALS")
  GlobalGT("Prep","LOCALS",0)
  HaveSpell(WIZARD_TIME_STOP)  // SPWI909.SPL (Time Stop)  
  OR(2)
    See(NearestEnemyOfType([GOODCUTOFF]))
    ActuallyInCombat()
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_TimeStopTimer","LOCALS",18)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_TIME_STOP)  // SPWI909.SPL (Time Stop)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// True Sight
/////////////////////////////////////////////////////////////////////
IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  HaveSpell(WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
  OR(6)
    SpellCast([GOODCUTOFF],WIZARD_PROJECT_IMAGE)  // SPWI703.SPL (Project Image)
    SpellCast([GOODCUTOFF],WIZARD_SIMULACRUM)  // SPWI804.SPL (Simulacrum)
    SpellCast([GOODCUTOFF],WIZARD_MISLEAD)  // SPWI607.SPL (Mislead)
    SpellCast([GOODCUTOFF],WIZARD_SHADOW_DOOR)  // SPWI505.SPL (Shadow Door)
    SpellCast([GOODCUTOFF],WIZARD_IMPROVED_INVISIBILITY)  // SPWI405.SPL (Improved Invisibility)
    SpellCast([GOODCUTOFF],WIZARD_INVISIBILITY)  // SPWI206.SPL (Invisibility)
  !CheckSpellState([GOODCUTOFF],SI_DIVINATION)
  Global("MO_EnemyTrueSight","GLOBAL",0)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
THEN
  RESPONSE #100
    SetGlobal("MO_TrueSightActive","LOCALS",1)
    SetGlobal("MO_EnemyTrueSight","GLOBAL",1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_EnemyTrueSightTimer","GLOBAL",60)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  HaveSpell(WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
  Detect([GOODCUTOFF])
  OR(4)
    StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
    CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
    Gender(LastSeenBy(Myself),ILLUSIONARY)
  !CheckSpellState([GOODCUTOFF],SI_DIVINATION)
  Global("MO_EnemyTrueSight","GLOBAL",0)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
THEN
  RESPONSE #100
    SetGlobal("MO_TrueSightActive","LOCALS",1)
    SetGlobal("MO_EnemyTrueSight","GLOBAL",1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_EnemyTrueSightTimer","GLOBAL",60)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  HaveSpell(WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
  See(NearestEnemyOf(Myself))
  OR(4)
    StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
    CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
    Gender(LastSeenBy(Myself),ILLUSIONARY)
  !CheckStat(LastSeenBy(Myself),3,WIZARD_SPELL_IMMUNITY)
  Global("MO_EnemyTrueSight","GLOBAL",0)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
THEN
  RESPONSE #100
    SetGlobal("MO_TrueSightActive","LOCALS",1)
    SetGlobal("MO_EnemyTrueSight","GLOBAL",1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_EnemyTrueSightTimer","GLOBAL",60)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  HaveSpell(WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
  See(SecondNearestEnemyOf(Myself))
  OR(4)
    StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
    CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
    Gender(LastSeenBy(Myself),ILLUSIONARY)
  !CheckStat(LastSeenBy(Myself),3,WIZARD_SPELL_IMMUNITY)
  Global("MO_EnemyTrueSight","GLOBAL",0)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
THEN
  RESPONSE #100
    SetGlobal("MO_TrueSightActive","LOCALS",1)
    SetGlobal("MO_EnemyTrueSight","GLOBAL",1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_EnemyTrueSightTimer","GLOBAL",60)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  HaveSpell(WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
  See(ThirdNearestEnemyOf(Myself))
  OR(4)
    StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
    CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
    Gender(LastSeenBy(Myself),ILLUSIONARY)
  !CheckStat(LastSeenBy(Myself),3,WIZARD_SPELL_IMMUNITY)
  Global("MO_EnemyTrueSight","GLOBAL",0)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
THEN
  RESPONSE #100
    SetGlobal("MO_TrueSightActive","LOCALS",1)
    SetGlobal("MO_EnemyTrueSight","GLOBAL",1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_EnemyTrueSightTimer","GLOBAL",60)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  HaveSpell(WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
  See(FourthNearestEnemyOf(Myself))
  OR(4)
    StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
    CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
    Gender(LastSeenBy(Myself),ILLUSIONARY)
  !CheckStat(LastSeenBy(Myself),3,WIZARD_SPELL_IMMUNITY)
  Global("MO_EnemyTrueSight","GLOBAL",0)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
THEN
  RESPONSE #100
    SetGlobal("MO_TrueSightActive","LOCALS",1)
    SetGlobal("MO_EnemyTrueSight","GLOBAL",1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_EnemyTrueSightTimer","GLOBAL",60)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  HaveSpell(WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
  See(FifthNearestEnemyOf(Myself))
  OR(4)
    StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
    CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
    Gender(LastSeenBy(Myself),ILLUSIONARY)
  !CheckStat(LastSeenBy(Myself),3,WIZARD_SPELL_IMMUNITY)
  Global("MO_EnemyTrueSight","GLOBAL",0)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
THEN
  RESPONSE #100
    SetGlobal("MO_TrueSightActive","LOCALS",1)
    SetGlobal("MO_EnemyTrueSight","GLOBAL",1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_EnemyTrueSightTimer","GLOBAL",60)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  HaveSpell(WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
  See(SixthNearestEnemyOf(Myself))
  OR(4)
    StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
    StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
    CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
    Gender(LastSeenBy(Myself),ILLUSIONARY)
  !CheckStat(LastSeenBy(Myself),3,WIZARD_SPELL_IMMUNITY)
  Global("MO_EnemyTrueSight","GLOBAL",0)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
THEN
  RESPONSE #100
    SetGlobal("MO_TrueSightActive","LOCALS",1)
    SetGlobal("MO_EnemyTrueSight","GLOBAL",1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_EnemyTrueSightTimer","GLOBAL",60)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Dispels
///////////////////////////////////////////////////////////////////// 
/////////////////////////////////////////////////////////////////////
// Spell: Khelben's Warding Whip
/////////////////////////////////////////////////////////////////////
IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  !GlobalTimerNotExpired("MO_TimeStopTimer","LOCALS")
  NumCreatureLT([GOODCUTOFF],4)
  See(NearestEnemyOfType([GOODCUTOFF]))
  HaveSpell(WIZARD_WARDING_WHIP)  // SPWI705.SPL (Khelben's Warding Whip)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(6)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
    CheckSpellState(LastSeenBy(Myself),SI_DIVINATION)
    CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_KHELBENS_WARDING_WHIP)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_WARDING_WHIP)  // SPWI705.SPL (Khelben's Warding Whip)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  !GlobalTimerNotExpired("MO_TimeStopTimer","LOCALS")
  NumCreatureLT([GOODCUTOFF],4)
  See(SecondNearestEnemyOfType([GOODCUTOFF]))
  HaveSpell(WIZARD_WARDING_WHIP)  // SPWI705.SPL (Khelben's Warding Whip)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(6)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
    CheckSpellState(LastSeenBy(Myself),SI_DIVINATION)
    CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_KHELBENS_WARDING_WHIP)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_WARDING_WHIP)  // SPWI705.SPL (Khelben's Warding Whip)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  !GlobalTimerNotExpired("MO_TimeStopTimer","LOCALS")
  NumCreatureLT([GOODCUTOFF],4)
  See(ThirdNearestEnemyOfType([GOODCUTOFF]))
  HaveSpell(WIZARD_WARDING_WHIP)  // SPWI705.SPL (Khelben's Warding Whip)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(6)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
    CheckSpellState(LastSeenBy(Myself),SI_DIVINATION)
    CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_KHELBENS_WARDING_WHIP)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_WARDING_WHIP)  // SPWI705.SPL (Khelben's Warding Whip)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  !GlobalTimerNotExpired("MO_TimeStopTimer","LOCALS")
  NumCreatureLT([GOODCUTOFF],4)
  See(FourthNearestEnemyOfType([GOODCUTOFF]))
  HaveSpell(WIZARD_WARDING_WHIP)  // SPWI705.SPL (Khelben's Warding Whip)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(6)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
    CheckSpellState(LastSeenBy(Myself),SI_DIVINATION)
    CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_KHELBENS_WARDING_WHIP)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_WARDING_WHIP)  // SPWI705.SPL (Khelben's Warding Whip)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  !GlobalTimerNotExpired("MO_TimeStopTimer","LOCALS")
  NumCreatureLT([GOODCUTOFF],4)
  See(FifthNearestEnemyOfType([GOODCUTOFF]))
  HaveSpell(WIZARD_WARDING_WHIP)  // SPWI705.SPL (Khelben's Warding Whip)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(6)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
    CheckSpellState(LastSeenBy(Myself),SI_DIVINATION)
    CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_KHELBENS_WARDING_WHIP)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_WARDING_WHIP)  // SPWI705.SPL (Khelben's Warding Whip)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  !GlobalTimerNotExpired("MO_TimeStopTimer","LOCALS")
  NumCreatureLT([GOODCUTOFF],4)
  See(SixthNearestEnemyOfType([GOODCUTOFF]))
  HaveSpell(WIZARD_WARDING_WHIP)  // SPWI705.SPL (Khelben's Warding Whip)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(6)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
    CheckSpellState(LastSeenBy(Myself),SI_DIVINATION)
    CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_KHELBENS_WARDING_WHIP)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_WARDING_WHIP)  // SPWI705.SPL (Khelben's Warding Whip)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Spell Type Determination
/////////////////////////////////////////////////////////////////////
IF
  RandomNum(2,1)
THEN
  RESPONSE #100
    SetGlobal("MO_Offensive","LOCALS",1)
    Continue()
END

IF
  RandomNum(2,2)
THEN
  RESPONSE #100
    SetGlobal("MO_Offensive","LOCALS",0)
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Offensive Spells
/////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////
// Spell: Dragon's Breath
/////////////////////////////////////////////////////////////////////
IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  See([GOODCUTOFF])
  HaveSpell(WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (Dragon's Breath)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #50
    SetGlobal("MO_CastDragonsBreath","LOCALS",1)
    Continue()
  RESPONSE #50
    SetGlobal("MO_CastDragonsBreath","LOCALS",0)
    Continue()
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastDragonsBreath","LOCALS",1)
  See(NearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  Range(LastSeenBy(Myself),5)
  HaveSpell(WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (Dragon's Breath)
  !Gender(LastSeenBy(Myself),SUMMONED)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (Dragon's Breath)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastDragonsBreath","LOCALS",1)
  See(SecondNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  Range(LastSeenBy(Myself),5)
  HaveSpell(WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (Dragon's Breath)
  !Gender(LastSeenBy(Myself),SUMMONED)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (Dragon's Breath)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastDragonsBreath","LOCALS",1)
  See(ThirdNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  Range(LastSeenBy(Myself),5)
  HaveSpell(WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (Dragon's Breath)
  !Gender(LastSeenBy(Myself),SUMMONED)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (Dragon's Breath)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastDragonsBreath","LOCALS",1)
  See(FourthNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  Range(LastSeenBy(Myself),5)
  HaveSpell(WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (Dragon's Breath)
  !Gender(LastSeenBy(Myself),SUMMONED)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (Dragon's Breath)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastDragonsBreath","LOCALS",1)
  See(FifthNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  Range(LastSeenBy(Myself),5)
  HaveSpell(WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (Dragon's Breath)
  !Gender(LastSeenBy(Myself),SUMMONED)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (Dragon's Breath)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastDragonsBreath","LOCALS",1)
  See(SixthNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  Range(LastSeenBy(Myself),5)
  HaveSpell(WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (Dragon's Breath)
  !Gender(LastSeenBy(Myself),SUMMONED)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (Dragon's Breath)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  See([GOODCUTOFF])
  HaveSpell(WIZARD_COMET)  // SPWI922.SPL (Dragon's Breath)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #50
    SetGlobal("MO_CastComet","LOCALS",1)
    Continue()
  RESPONSE #50
    SetGlobal("MO_CastComet","LOCALS",0)
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Spell: Comet
/////////////////////////////////////////////////////////////////////
IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastComet","LOCALS",1)
  See(NearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  Range(LastSeenBy(Myself),10)
  HaveSpell(WIZARD_COMET)  // SPWI925.SPL (Comet)
  !Gender(LastSeenBy(Myself),SUMMONED)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
  CheckStatLT(LastSeenBy(Myself),55,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (Comet)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastComet","LOCALS",1)
  See(SecondNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  Range(LastSeenBy(Myself),10)
  HaveSpell(WIZARD_COMET)  // SPWI925.SPL (Comet)
  !Gender(LastSeenBy(Myself),SUMMONED)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
  CheckStatLT(LastSeenBy(Myself),55,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (Comet)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastComet","LOCALS",1)
  See(ThirdNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  Range(LastSeenBy(Myself),10)
  HaveSpell(WIZARD_COMET)  // SPWI925.SPL (Comet)
  !Gender(LastSeenBy(Myself),SUMMONED)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
  CheckStatLT(LastSeenBy(Myself),55,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (Comet)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastComet","LOCALS",1)
  See(FourthNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  Range(LastSeenBy(Myself),10)
  HaveSpell(WIZARD_COMET)  // SPWI925.SPL (Comet)
  !Gender(LastSeenBy(Myself),SUMMONED)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
  CheckStatLT(LastSeenBy(Myself),55,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (Comet)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastComet","LOCALS",1)
  See(FifthNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  Range(LastSeenBy(Myself),10)
  HaveSpell(WIZARD_COMET)  // SPWI925.SPL (Comet)
  !Gender(LastSeenBy(Myself),SUMMONED)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
  CheckStatLT(LastSeenBy(Myself),55,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (Comet)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastComet","LOCALS",1)
  See(SixthNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  Range(LastSeenBy(Myself),10)
  HaveSpell(WIZARD_COMET)  // SPWI925.SPL (Comet)
  !Gender(LastSeenBy(Myself),SUMMONED)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
  CheckStatLT(LastSeenBy(Myself),55,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (Comet)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Spell: Abi-Dalzim's Horrid Wilting
/////////////////////////////////////////////////////////////////////

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  !GlobalTimerNotExpired("MO_AbiTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  See([GOODCUTOFF])
  HaveSpell(WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #50
    SetGlobal("MO_CastAbiDalzim","LOCALS",1)
    Continue()
  RESPONSE #50
    SetGlobal("MO_CastAbiDalzim","LOCALS",0)
    Continue()
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastAbiDalzim","LOCALS",1)
  See(NearestEnemyOfType([GOODCUTOFF]))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
  !CheckSpellState(LastSeenBy(Myself),SI_NECROMANCY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),80,RESISTMAGIC)
  CheckStatLT(LastSeenBy(Myself),80,MAGICDAMAGERESISTANCE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_AbiTimer","LOCALS",12)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastAbiDalzim","LOCALS",1)
  See(SecondNearestEnemyOfType([GOODCUTOFF]))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
  !CheckSpellState(LastSeenBy(Myself),SI_NECROMANCY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),80,RESISTMAGIC)
  CheckStatLT(LastSeenBy(Myself),80,MAGICDAMAGERESISTANCE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_AbiTimer","LOCALS",12)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastAbiDalzim","LOCALS",1)
  See(ThirdNearestEnemyOfType([GOODCUTOFF]))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
  !CheckSpellState(LastSeenBy(Myself),SI_NECROMANCY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),80,RESISTMAGIC)
  CheckStatLT(LastSeenBy(Myself),80,MAGICDAMAGERESISTANCE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_AbiTimer","LOCALS",12)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastAbiDalzim","LOCALS",1)
  See(FourthNearestEnemyOfType([GOODCUTOFF]))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
  !CheckSpellState(LastSeenBy(Myself),SI_NECROMANCY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),80,RESISTMAGIC)
  CheckStatLT(LastSeenBy(Myself),80,MAGICDAMAGERESISTANCE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_AbiTimer","LOCALS",12)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastAbiDalzim","LOCALS",1)
  See(FifthNearestEnemyOfType([GOODCUTOFF]))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
  !CheckSpellState(LastSeenBy(Myself),SI_NECROMANCY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),80,RESISTMAGIC)
  CheckStatLT(LastSeenBy(Myself),80,MAGICDAMAGERESISTANCE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_AbiTimer","LOCALS",12)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastAbiDalzim","LOCALS",1)
  See(SixthNearestEnemyOfType([GOODCUTOFF]))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
  !CheckSpellState(LastSeenBy(Myself),SI_NECROMANCY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),80,RESISTMAGIC)
  CheckStatLT(LastSeenBy(Myself),80,MAGICDAMAGERESISTANCE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_AbiTimer","LOCALS",12)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Spell: Power Word, Kill
/////////////////////////////////////////////////////////////////////
IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  See([GOODCUTOFF])
  HaveSpell(WIZARD_POWER_WORD_KILL)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #50
    SetGlobal("MO_CastPowerWordKill","LOCALS",1)
    Continue()
  RESPONSE #50
    SetGlobal("MO_CastPowerWordKill","LOCALS",0)
    Continue()
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastPowerWordKill","LOCALS",1)
  See(NearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_POWER_WORD_KILL)
  HPLT(LastSeenBy(Myself),61)
  !Gender(LastSeenBy(Myself),SUMMONED)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_KILL)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastPowerWordKill","LOCALS",1)
  See(SecondNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_POWER_WORD_KILL)
  HPLT(LastSeenBy(Myself),61)
  !Gender(LastSeenBy(Myself),SUMMONED)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_KILL)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastPowerWordKill","LOCALS",1)
  See(ThirdNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_POWER_WORD_KILL)
  HPLT(LastSeenBy(Myself),61)
  !Gender(LastSeenBy(Myself),SUMMONED)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_KILL)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastPowerWordKill","LOCALS",1)
  See(FourthNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_POWER_WORD_KILL)
  HPLT(LastSeenBy(Myself),61)
  !Gender(LastSeenBy(Myself),SUMMONED)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_KILL)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastPowerWordKill","LOCALS",1)
  See(FifthNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_POWER_WORD_KILL)
  HPLT(LastSeenBy(Myself),61)
  !Gender(LastSeenBy(Myself),SUMMONED)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_KILL)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastPowerWordKill","LOCALS",1)
  See(SixthNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_POWER_WORD_KILL)
  HPLT(LastSeenBy(Myself),61)
  !Gender(LastSeenBy(Myself),SUMMONED)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_KILL)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Spell: Death Spell
/////////////////////////////////////////////////////////////////////
IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  See([GOODCUTOFF.0.0.0.0.SUMMONED])
  HaveSpell(WIZARD_DEATH_SPELL)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #80
    SetGlobal("MO_CastDeathSpell","LOCALS",1)
    Continue()
  RESPONSE #20
    SetGlobal("MO_CastDeathSpell","LOCALS",0)
    Continue()
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastDeathSpell","LOCALS",1)
  See(Nearest([GOODCUTOFF.0.0.0.0.SUMMONED]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_DEATH_SPELL)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_DEATH_SPELL)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastDeathSpell","LOCALS",1)
  See(SecondNearest([GOODCUTOFF.0.0.0.0.SUMMONED]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_DEATH_SPELL)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_DEATH_SPELL)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastDeathSpell","LOCALS",1)
  See(ThirdNearest([GOODCUTOFF.0.0.0.0.SUMMONED]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_DEATH_SPELL)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_DEATH_SPELL)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastDeathSpell","LOCALS",1)
  See(FourthNearest([GOODCUTOFF.0.0.0.0.SUMMONED]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_DEATH_SPELL)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_DEATH_SPELL)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastDeathSpell","LOCALS",1)
  See(FifthNearest([GOODCUTOFF.0.0.0.0.SUMMONED]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_DEATH_SPELL)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_DEATH_SPELL)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastDeathSpell","LOCALS",1)
  See(SixthNearest([GOODCUTOFF.0.0.0.0.SUMMONED]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_DEATH_SPELL)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_DEATH_SPELL)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Spell: Finger of Death
/////////////////////////////////////////////////////////////////////
IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  See([GOODCUTOFF])
  HaveSpell(WIZARD_FINGER_OF_DEATH)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #50
    SetGlobal("MO_CastFingerDeath","LOCALS",1)
    Continue()
  RESPONSE #50
    SetGlobal("MO_CastFingerDeath","LOCALS",0)
    Continue()
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastFingerDeath","LOCALS",1)
  See(NearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_FINGER_OF_DEATH)
  !HasItemEquiped("clck26",LastSeenBy(Myself))  // Cloak of Mirroring
  !CheckStat(LastSeenBy(Myself),1,DEATH_WARD)
  !CheckSpellState(LastSeenBy(Myself),SI_NECROMANCY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),40,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastFingerDeath","LOCALS",1)
  See(SecondNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_FINGER_OF_DEATH)
  !HasItemEquiped("clck26",LastSeenBy(Myself))  // Cloak of Mirroring
  !CheckStat(LastSeenBy(Myself),1,DEATH_WARD)
  !CheckSpellState(LastSeenBy(Myself),SI_NECROMANCY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),40,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastFingerDeath","LOCALS",1)
  See(ThirdNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_FINGER_OF_DEATH)
  !HasItemEquiped("clck26",LastSeenBy(Myself))  // Cloak of Mirroring
  !CheckStat(LastSeenBy(Myself),1,DEATH_WARD)
  !CheckSpellState(LastSeenBy(Myself),SI_NECROMANCY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),40,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastFingerDeath","LOCALS",1)
  See(FourthNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_FINGER_OF_DEATH)
  !HasItemEquiped("clck26",LastSeenBy(Myself))  // Cloak of Mirroring
  !CheckStat(LastSeenBy(Myself),1,DEATH_WARD)
  !CheckSpellState(LastSeenBy(Myself),SI_NECROMANCY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),40,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastFingerDeath","LOCALS",1)
  See(FifthNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_FINGER_OF_DEATH)
  !HasItemEquiped("clck26",LastSeenBy(Myself))  // Cloak of Mirroring
  !CheckStat(LastSeenBy(Myself),1,DEATH_WARD)
  !CheckSpellState(LastSeenBy(Myself),SI_NECROMANCY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),40,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",1)
  Global("MO_CastFingerDeath","LOCALS",1)
  See(SixthNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_FINGER_OF_DEATH)
  !HasItemEquiped("clck26",LastSeenBy(Myself))  // Cloak of Mirroring
  !CheckStat(LastSeenBy(Myself),1,DEATH_WARD)
  !CheckSpellState(LastSeenBy(Myself),SI_NECROMANCY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(LastSeenBy(Myself),40,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Defensive Spells
/////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////
// Spell: Improved Alacrity
/////////////////////////////////////////////////////////////////////
IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  !GlobalTimerNotExpired("MO_TimeStopTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  See(NearestEnemyOfType([GOODCUTOFF]))
  HaveSpell(WIZARD_IMPROVED_ALUCRITY)  // SPWI921.SPL (Improved Alacrity)
  !HaveSpell(WIZARD_TIME_STOP)  // SPWI909.SPL (Time Stop) 
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #80
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_IMPROVED_ALUCRITY)  // SPWI921.SPL (Improved Alacrity)
    SetInterrupt(TRUE)
  RESPONSE #20
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Spell: Spell Turning
/////////////////////////////////////////////////////////////////////
IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  OR(7)
    See([GOODCUTOFF.0.0.MAGE_ALL])
    See([GOODCUTOFF.0.0.BARD_ALL])
    See([GOODCUTOFF.0.0.CLERIC_ALL])
    See([GOODCUTOFF.0.0.DRUID_ALL])
    See([GOODCUTOFF.0.0.SORCERER])
    See([GOODCUTOFF.0.0.CLERIC_MAGE])
    See([GOODCUTOFF.0.0.MAGE_ALL])
  HaveSpell(WIZARD_SPELL_TURNING)  // SPWI701.SPL (Spell Turning)
  CheckStatLT(Myself,1,WIZARD_SPELL_TURNING)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #50
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_SPELL_TURNING)  // SPWI701.SPL (Spell Turning)
    SetInterrupt(TRUE)
  RESPONSE #50
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Spell: Maze
/////////////////////////////////////////////////////////////////////
IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  !GlobalTimerNotExpired("MO_MazeTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  See([GOODCUTOFF])
  HaveSpell(WIZARD_MAZE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #50
    SetGlobal("MO_CastMaze","LOCALS",1)
    Continue()
  RESPONSE #50
    SetGlobal("MO_CastMaze","LOCALS",0)
    Continue()
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  !GlobalTimerNotExpired("MO_MazeTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  Global("MO_CastMaze","LOCALS",1)
  See(NearestEnemyOf(Myself))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  Range(LastSeenBy(Myself),4)
  HaveSpell(WIZARD_MAZE)
  !Gender(LastSeenBy(Myself),SUMMONED)
  CheckStatLT(LastSeenBy(Myself),18,INT)
  !CheckSpellState(LastSeenBy(Myself),CHAOTIC_COMMANDS)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !Kit(LastSeenBy(Myself),BERSERKER)
  !Kit(LastSeenBy(Myself),BARBARIAN)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_MazeTimer","LOCALS",18)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_MAZE)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  !GlobalTimerNotExpired("MO_MazeTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  Global("MO_CastMaze","LOCALS",1)
  See(SecondNearestEnemyOf(Myself))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  Range(LastSeenBy(Myself),4)
  HaveSpell(WIZARD_MAZE)
  !Gender(LastSeenBy(Myself),SUMMONED)
  CheckStatLT(LastSeenBy(Myself),18,INT)
  !CheckSpellState(LastSeenBy(Myself),CHAOTIC_COMMANDS)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !Kit(LastSeenBy(Myself),BERSERKER)
  !Kit(LastSeenBy(Myself),BARBARIAN)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_MazeTimer","LOCALS",18)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_MAZE)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  !GlobalTimerNotExpired("MO_MazeTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  Global("MO_CastMaze","LOCALS",1)
  See(ThirdNearestEnemyOf(Myself))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  Range(LastSeenBy(Myself),4)
  HaveSpell(WIZARD_MAZE)
  !Gender(LastSeenBy(Myself),SUMMONED)
  CheckStatLT(LastSeenBy(Myself),18,INT)
  !CheckSpellState(LastSeenBy(Myself),CHAOTIC_COMMANDS)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !Kit(LastSeenBy(Myself),BERSERKER)
  !Kit(LastSeenBy(Myself),BARBARIAN)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_MazeTimer","LOCALS",18)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_MAZE)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  !GlobalTimerNotExpired("MO_MazeTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  Global("MO_CastMaze","LOCALS",1)
  See(FourthNearestEnemyOf(Myself))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  Range(LastSeenBy(Myself),4)
  HaveSpell(WIZARD_MAZE)
  !Gender(LastSeenBy(Myself),SUMMONED)
  CheckStatLT(LastSeenBy(Myself),18,INT)
  !CheckSpellState(LastSeenBy(Myself),CHAOTIC_COMMANDS)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !Kit(LastSeenBy(Myself),BERSERKER)
  !Kit(LastSeenBy(Myself),BARBARIAN)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_MazeTimer","LOCALS",18)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_MAZE)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  !GlobalTimerNotExpired("MO_MazeTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  Global("MO_CastMaze","LOCALS",1)
  See(FifthNearestEnemyOf(Myself))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  Range(LastSeenBy(Myself),4)
  HaveSpell(WIZARD_MAZE)
  !Gender(LastSeenBy(Myself),SUMMONED)
  CheckStatLT(LastSeenBy(Myself),18,INT)
  !CheckSpellState(LastSeenBy(Myself),CHAOTIC_COMMANDS)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !Kit(LastSeenBy(Myself),BERSERKER)
  !Kit(LastSeenBy(Myself),BARBARIAN)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_MazeTimer","LOCALS",18)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_MAZE)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  !GlobalTimerNotExpired("MO_MazeTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  Global("MO_CastMaze","LOCALS",1)
  See(SixthNearestEnemyOf(Myself))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  Range(LastSeenBy(Myself),4)
  HaveSpell(WIZARD_MAZE)
  !Gender(LastSeenBy(Myself),SUMMONED)
  CheckStatLT(LastSeenBy(Myself),18,INT)
  !CheckSpellState(LastSeenBy(Myself),CHAOTIC_COMMANDS)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !Kit(LastSeenBy(Myself),BERSERKER)
  !Kit(LastSeenBy(Myself),BARBARIAN)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_MazeTimer","LOCALS",18)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_MAZE)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Spell: Power Word, Blind
/////////////////////////////////////////////////////////////////////
IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  See([GOODCUTOFF])
  HaveSpell(WIZARD_POWER_WORD_BLIND)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #50
    SetGlobal("MO_CastPowerWordBlind","LOCALS",1)
    Continue()
  RESPONSE #50
    SetGlobal("MO_CastPowerWordBlind","LOCALS",0)
    Continue()
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  Global("MO_CastPowerWordBlind","LOCALS",1)
  See(NearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_POWER_WORD_BLIND)
  !HasItemEquiped("NPMISC1",LastSeenBy(Myself))
  !Gender(LastSeenBy(Myself),SUMMONED)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  !StateCheck(LastSeenBy(Myself),STATE_BLIND)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_BLIND)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  Global("MO_CastPowerWordBlind","LOCALS",1)
  See(SecondNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_POWER_WORD_BLIND)
  !HasItemEquiped("NPMISC1",LastSeenBy(Myself))
  !Gender(LastSeenBy(Myself),SUMMONED)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  !StateCheck(LastSeenBy(Myself),STATE_BLIND)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_BLIND)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  Global("MO_CastPowerWordBlind","LOCALS",1)
  See(ThirdNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_POWER_WORD_BLIND)
  !HasItemEquiped("NPMISC1",LastSeenBy(Myself))
  !Gender(LastSeenBy(Myself),SUMMONED)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  !StateCheck(LastSeenBy(Myself),STATE_BLIND)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_BLIND)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  Global("MO_CastPowerWordBlind","LOCALS",1)
  See(FourthNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_POWER_WORD_BLIND)
  !HasItemEquiped("NPMISC1",LastSeenBy(Myself))
  !Gender(LastSeenBy(Myself),SUMMONED)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  !StateCheck(LastSeenBy(Myself),STATE_BLIND)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_BLIND)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  Global("MO_CastPowerWordBlind","LOCALS",1)
  See(FifthNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_POWER_WORD_BLIND)
  !HasItemEquiped("NPMISC1",LastSeenBy(Myself))
  !Gender(LastSeenBy(Myself),SUMMONED)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  !StateCheck(LastSeenBy(Myself),STATE_BLIND)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_BLIND)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  Global("MO_CastPowerWordBlind","LOCALS",1)
  See(SixthNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_POWER_WORD_BLIND)
  !HasItemEquiped("NPMISC1",LastSeenBy(Myself))
  !Gender(LastSeenBy(Myself),SUMMONED)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  !StateCheck(LastSeenBy(Myself),STATE_BLIND)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_BLIND)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Spell: Summon Efreeti
/////////////////////////////////////////////////////////////////////
IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  See([GOODCUTOFF])
  HaveSpell(WIZARD_SUMMON_EFREET)  // SPWI717.SPL (Summon Efreeti)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #50
    SetGlobal("MO_CastEfreeti","LOCALS",1)
    Continue()
  RESPONSE #50
    SetGlobal("MO_CastEfreeti","LOCALS",0)
    Continue()
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  Global("MO_CastEfreeti","LOCALS",1)
  See(NearestEnemyOfType([GOODCUTOFF]))
  HaveSpell(WIZARD_SUMMON_EFREET)  // SPWI717.SPL (Summon Efreeti)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_SUMMON_EFREET)  // SPWI717.SPL (Summon Efreeti)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Spell: Summon Hakeashar
/////////////////////////////////////////////////////////////////////
IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  See([GOODCUTOFF])
  HaveSpell(WIZARD_SUMMON_HAKEASHAR)  // SPWI719.SPL (Summon Hakeashar)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #50
    SetGlobal("MO_CastHakeashar","LOCALS",1)
    Continue()
  RESPONSE #50
    SetGlobal("MO_CastHakeashar","LOCALS",0)
    Continue()
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  Global("MO_CastHakeashar","LOCALS",1)
  See(NearestEnemyOfType([GOODCUTOFF]))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_SUMMON_HAKEASHAR)  // SPWI719.SPL (Summon Hakeashar)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  OR(5)
    Class(LastSeenBy(Myself),MAGE_ALL)
    Class(LastSeenBy(Myself),BARD_ALL)
    Class(LastSeenBy(Myself),CLERIC_ALL)
    Class(LastSeenBy(Myself),DRUID_ALL)
    Class(LastSeenBy(Myself),SORCERER)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_SUMMON_HAKEASHAR)  // SPWI719.SPL (Summon Hakeashar)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  Global("MO_CastHakeashar","LOCALS",1)
  See(SecondNearestEnemyOfType([GOODCUTOFF]))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_SUMMON_HAKEASHAR)  // SPWI719.SPL (Summon Hakeashar)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  OR(5)
    Class(LastSeenBy(Myself),MAGE_ALL)
    Class(LastSeenBy(Myself),BARD_ALL)
    Class(LastSeenBy(Myself),CLERIC_ALL)
    Class(LastSeenBy(Myself),DRUID_ALL)
    Class(LastSeenBy(Myself),SORCERER)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_SUMMON_HAKEASHAR)  // SPWI719.SPL (Summon Hakeashar)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  Global("MO_CastHakeashar","LOCALS",1)
  See(ThirdNearestEnemyOfType([GOODCUTOFF]))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_SUMMON_HAKEASHAR)  // SPWI719.SPL (Summon Hakeashar)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  OR(5)
    Class(LastSeenBy(Myself),MAGE_ALL)
    Class(LastSeenBy(Myself),BARD_ALL)
    Class(LastSeenBy(Myself),CLERIC_ALL)
    Class(LastSeenBy(Myself),DRUID_ALL)
    Class(LastSeenBy(Myself),SORCERER)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_SUMMON_HAKEASHAR)  // SPWI719.SPL (Summon Hakeashar)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  Global("MO_CastHakeashar","LOCALS",1)
  See(FourthNearestEnemyOfType([GOODCUTOFF]))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_SUMMON_HAKEASHAR)  // SPWI719.SPL (Summon Hakeashar)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  OR(5)
    Class(LastSeenBy(Myself),MAGE_ALL)
    Class(LastSeenBy(Myself),BARD_ALL)
    Class(LastSeenBy(Myself),CLERIC_ALL)
    Class(LastSeenBy(Myself),DRUID_ALL)
    Class(LastSeenBy(Myself),SORCERER)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_SUMMON_HAKEASHAR)  // SPWI719.SPL (Summon Hakeashar)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  Global("MO_CastHakeashar","LOCALS",1)
  See(FifthNearestEnemyOfType([GOODCUTOFF]))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_SUMMON_HAKEASHAR)  // SPWI719.SPL (Summon Hakeashar)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  OR(5)
    Class(LastSeenBy(Myself),MAGE_ALL)
    Class(LastSeenBy(Myself),BARD_ALL)
    Class(LastSeenBy(Myself),CLERIC_ALL)
    Class(LastSeenBy(Myself),DRUID_ALL)
    Class(LastSeenBy(Myself),SORCERER)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_SUMMON_HAKEASHAR)  // SPWI719.SPL (Summon Hakeashar)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  Global("MO_CastHakeashar","LOCALS",1)
  See(SixthNearestEnemyOfType([GOODCUTOFF]))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_SUMMON_HAKEASHAR)  // SPWI719.SPL (Summon Hakeashar)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  OR(5)
    Class(LastSeenBy(Myself),MAGE_ALL)
    Class(LastSeenBy(Myself),BARD_ALL)
    Class(LastSeenBy(Myself),CLERIC_ALL)
    Class(LastSeenBy(Myself),DRUID_ALL)
    Class(LastSeenBy(Myself),SORCERER)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_SUMMON_HAKEASHAR)  // SPWI719.SPL (Summon Hakeashar)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Spell: Mordenkainen's Sword
/////////////////////////////////////////////////////////////////////
IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  See(NearestEnemyOfType([GOODCUTOFF]))
  HaveSpell(WIZARD_MORDENKAINENS_SWORD)  // SPWI716.SPL (Mordenkainen's Sword)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #50
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_MORDENKAINENS_SWORD)  // SPWI716.SPL (Mordenkainen's Sword)
    SetInterrupt(TRUE)
  RESPONSE #50
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Spell: Power Word, Stun
/////////////////////////////////////////////////////////////////////
IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  See([GOODCUTOFF])
  HaveSpell(WIZARD_POWER_WORD_STUN)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #50
    SetGlobal("MO_CastPowerWordStun","LOCALS",1)
    Continue()
  RESPONSE #50
    SetGlobal("MO_CastPowerWordStun","LOCALS",0)
    Continue()
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  Global("MO_CastPowerWordStun","LOCALS",1)
  See([PC.0.0.MAGE_ALL])
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HPLT(LastSeenBy(Myself),90)
  HaveSpell(WIZARD_POWER_WORD_STUN)
  HPPercentLT(LastSeenBy(Myself),60)
  !Gender(LastSeenBy(Myself),SUMMONED)
  !CheckSpellState(LastSeenBy(Myself),BARBARIAN_RAGE)
  !CheckSpellState(LastSeenBy(Myself),BERSERKER_RAGE)
  !CheckSpellState(LastSeenBy(Myself),MINSC_BERSERK)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(LastSeenBy(Myself),CHAOTIC_COMMANDS)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_STUN)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  Global("MO_CastPowerWordStun","LOCALS",1)
  See([PC.0.0.BARD])
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HPLT(LastSeenBy(Myself),90)
  HaveSpell(WIZARD_POWER_WORD_STUN)
  HPPercentLT(LastSeenBy(Myself),60)
  !Gender(LastSeenBy(Myself),SUMMONED)
  !CheckSpellState(LastSeenBy(Myself),BARBARIAN_RAGE)
  !CheckSpellState(LastSeenBy(Myself),BERSERKER_RAGE)
  !CheckSpellState(LastSeenBy(Myself),MINSC_BERSERK)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(LastSeenBy(Myself),CHAOTIC_COMMANDS)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_STUN)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  Global("MO_CastPowerWordStun","LOCALS",1)
  See([PC.0.0.THIEF_ALL])
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HPLT(LastSeenBy(Myself),90)
  HaveSpell(WIZARD_POWER_WORD_STUN)
  HPPercentLT(LastSeenBy(Myself),60)
  !Gender(LastSeenBy(Myself),SUMMONED)
  !CheckSpellState(LastSeenBy(Myself),BARBARIAN_RAGE)
  !CheckSpellState(LastSeenBy(Myself),BERSERKER_RAGE)
  !CheckSpellState(LastSeenBy(Myself),MINSC_BERSERK)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(LastSeenBy(Myself),CHAOTIC_COMMANDS)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_STUN)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  Global("MO_Offensive","LOCALS",0)
  Global("MO_CastPowerWordStun","LOCALS",1)
  See([PC.0.0.CLERIC_ALL])
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HPLT(LastSeenBy(Myself),90)
  HaveSpell(WIZARD_POWER_WORD_STUN)
  HPPercentLT(LastSeenBy(Myself),60)
  !Gender(LastSeenBy(Myself),SUMMONED)
  !CheckSpellState(LastSeenBy(Myself),BARBARIAN_RAGE)
  !CheckSpellState(LastSeenBy(Myself),BERSERKER_RAGE)
  !CheckSpellState(LastSeenBy(Myself),MINSC_BERSERK)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckSpellState(LastSeenBy(Myself),CHAOTIC_COMMANDS)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_STUN)
    SetInterrupt(TRUE)
END