// Tactics Remix, Kensai Ryu's Improved Copper Coronet

///////////////////////////////////////////////////////////////////////////
// Copy .BCS file to override folder                                     //
///////////////////////////////////////////////////////////////////////////
EXTEND_TOP ~AR0406.BCS~ ~tactics-remix/baf/copper/new.baf~
COPY ~tactics-remix/baf/copper/gorf.baf~ ~override/gorf.bcs~
  COMPILE_BAF_TO_BCS
  