// Tactics Remix, Morpheus562's Improved Drizzt

///////////////////////////////////////////////////////////////////////////
// Import Files                                                          //
///////////////////////////////////////////////////////////////////////////
COPY_EXISTING ~DRIZZT.CRE~ ~override~
  WRITE_BYTE 0x59 50 // Fire Resist
  REPLACE_CRE_ITEM ~BOOT01~ #0 #0 #0 ~UNSTEALABLE~ ~BOOTS~ EQUIP
  ADD_CRE_ITEM ~POTN26~ #1 #0 #0 ~UNSTEALABLE~ ~QITEM1~
  ADD_CRE_ITEM ~POTN52~ #2 #0 #0 ~UNSTEALABLE~ ~QITEM2~

///////////////////////////////////////////////////////////////////////////
// Copy .BCS file to override folder                                     //
///////////////////////////////////////////////////////////////////////////
COPY ~tactics-remix/baf/drizzt.baf~ ~override/drizzt.bcs~
  COMPILE_BAF_TO_BCS

